---
title: "Fig_1D_new"
author: "Max Schubert"
date: "8/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(data.table)
require(scales)
library(ggpubr)

parent_folder = here::here('fig_1D_new')
```

### comparison of recombinases

```{r get data}
#edit_data_path = '/Users/Max_Schubert/dropbox_hms/active_seq_reads/NovNextseq/FC_04398/Unaligned_1234_PF_mm1/Data/edit_mergedbins'

edit_data_file = paste(parent_folder,"1D_edit_merged_bins", sep = "/" )
edit_data_dt <- data.table(fread(edit_data_file))
edit_data_melt <- melt(edit_data_dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
#make new col SampleNum for merging to info
edit_data_melt[, SampleNum := as.numeric(str_replace_all(Sample, "_cutcount", ""))]

#create a column with total reads obs in each sample, filter out weak samples
s1.dt <- edit_data_melt[,  sample_total := sum(Count), by= 'Sample' ]
#take a peek at total reads unique(withtotals$sample_total)
s1.dt <- s1.dt[s1.dt$sample_total > 1000, ]
s1.dt<- s1.dt[Count > 10]
#s1.dt <- s1.dt[, unique_id := as.numeric(gsub('_cutcount','',Sample)) ]

```

```{r get metadata}

#import ref/alt sequences for each sample
#info_path = "/Users/Max_Schubert/Dropbox/RLR_e.coli_dropbox/NewNotebook_expts/C_delivery_other/c17_gDNA_second_try"
edit_info <- paste(parent_folder,"edit_df.csv", sep = "/" )
edit_info_dt <- data.table(fread(edit_info)) 

#merge ref and alt to main data 
melt_with_annot <- edit_data_melt[edit_info_dt, on = "SampleNum", nomatch = 0]


melt_with_annot[, is_ref := (bc_read == ref)]
melt_with_annot[, is_alt := (bc_read == alt)]

#measure edited fraction, on condition that sequence is ref or alt sequences
melt_with_fedit <- melt_with_annot[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := 1- (Count/sum(Count)) , by='SampleNum'][is_ref == TRUE]

#ditch a bunch of columns that i'm not using, for readability
melt_with_fedit[,c("read_id",
                   "V1",
                   "idx_7",
                   "idx7_index",
                   "idx_5",
                   "idx5_index",
                   "sample_nickname",
                   "lib",
                   "rep",
                   "tmp_conc",
                   "comment",
                   "time_treatment",
                   "5prime_cutadapt",
                   "3prime_cutadapt",
                   "5prime_edit",
                   "3prime_edit",
                   "ref",
                   "alt",
                   "is_ref",
                   "is_alt") :=NULL]


#read in txformations annotations:
tx_info_path = "/Users/Max_Schubert/Dropbox/RLR_e.coli_dropbox/NewNotebook_expts/B_openretrons/b15_new_recombinases"
tx_info <- paste(tx_info_path,"txdeets_recombinases.csv", sep = "/" )
tx_info_dt <- data.table(fread(tx_info)) 
#read in platemap
platemap <- paste(tx_info_path,"platemap.csv", sep = "/" )
platemap_dt <- data.table(fread(platemap)) 
#merge these, then merge to measured fractions of editing
key <- platemap_dt[tx_info_dt, on = "tx", nomatch = 0]
fedit_ready <- melt_with_fedit[key, on = "Well Position", nomatch = 0]

```

```{r plot}

##### alternative version that doesn't summarize the data

#filters
plotnow <-fedit_ready[timepoint == 2, ]
plotnow <- plotnow[recombinase != 'PF020/ssb150']


#reorder x axis in custom order:
plotnow$recombinase <-factor(plotnow$recombinase, levels=c('gfp_control',
                                                        'Beta',
                                                        'SR11',
                                                        'PF020'))

plotnow$locus <-factor(plotnow$locus, levels=c("gyr", "gfp", "rif"))

fig1D <- ggplot(plotnow, aes(x=recombinase, y=fraction_edited, color=locus)) + 
  geom_jitter(width = 0.15, height = 0.01, size = 3, alpha = 0.7) +
  theme_linedraw() +
  scale_y_continuous(breaks = c( .01, .1, .25, .5, .75, .9, 1),
                     labels = c('1%', '10%', '25%', '50%', '75%', '90%', '100%')) +
  theme(text = element_text(size=16),
        panel.grid.minor.y=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        legend.position = c(0.1, .85),
        #legend.box = "horizontal",
        #legend.direction = "horizontal"
        legend.title = element_blank()) +
  labs(
    x = "Single-Stranded Annealing Protein (SSAP) used",
    y = "Fraction Edited")+
  stat_compare_means(comparisons = list( c("gfp_control", "Beta"), c("Beta", "SR11"), c("Beta","PF020")  ),
                     method = "t.test", label.y = c(.5, .75, .9),
                     label = "p.val", tip.length = 0.01)

#save pdf
ggsave(here::here('fig_1dnew.pdf'), plot=fig1D, width=6, 
       height=4, units='in', dpi=300)
```

