---
title: "Fig2b"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(grid)
library(gridExtra)
library(here)
library(ggpubr)
library(here)

parent_folder <- here::here('fig_2bc')
```

```{r mergebins_liblist}
mergebinpath <- paste(parent_folder,"merged_TC_march2019", sep = "/" )
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt.dt[, SampleNum := str_replace_all(Sample, "_cutcount", "")]
rm(merged_bins.dt) #remove original

#metadata
liblistpath <- paste(parent_folder,"b26_TC_metadata.csv", sep = "/" )
liblistdt <- data.table(fread(liblistpath))

#### get donors, merge to create annotated table
allelelistpath <- paste(parent_folder,"allele_annotated_list_UPDATE.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]

#merge sample and seq metadata to big table
annotated_megatable <- liblistdt[mergemelt.dt, on = "SampleNum", nomatch = 0]
rm(mergemelt.dt) #remove original, large file
seq_annotated_megatable <- annotated_megatable[seq_annot_dt, on = "bc_read", nomatch = 0]

#print statement about merge efficiency
num_merged = sum(annotated_megatable$Count)
rm(annotated_megatable) #remove original, millions of rows
num_annot = sum(seq_annotated_megatable$Count)
pct_annot = num_annot/num_merged
num_merged = as.character(num_merged)
num_annot = as.character(num_annot)
pct_annot = as.character(pct_annot)




print(paste(num_annot, "reads annotated of",
            num_merged, "total reads, or",
            pct_annot, "%", sep = " "))
```

```{r PULL_NEW_DATA}
mergebinpath2 <- paste(parent_folder,"H6_merged_bins", sep = "/" )
merged_bins2.dt <- data.table(fread(mergebinpath2))
mergemelt2.dt <- melt(merged_bins2.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt2.dt[, SampleNum := str_replace_all(Sample, "_cutcount", "")]
rm(merged_bins2.dt) #remove original

#metadata
liblistpath2 <- paste(parent_folder,"liblistH6.csv", sep = "/" )
liblistdt2 <- data.table(fread(liblistpath2))
liblistdt2[,SampleNum := as.character(SampleNum)]
#liblistdt2[,samplenum:= NULL]


allelelistpath <- paste(parent_folder,"allele_annotated_list.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]

#merge sample and seq metadata to big table
annotated_megatable2 <- liblistdt2[mergemelt2.dt, on = "SampleNum", nomatch = 0]
rm(mergemelt2.dt) #remove original, millions of rows
seq_annotated_megatable2 <- annotated_megatable2[seq_annot_dt, on = "bc_read", nomatch = 0]

#print statement about merge efficiency
num_merged = sum(annotated_megatable2$Count)
rm(annotated_megatable2) #remove original, millions of rows
num_annot = sum(seq_annotated_megatable2$Count)
pct_annot = num_annot/num_merged
num_merged = as.character(num_merged)
num_annot = as.character(num_annot)
pct_annot = as.character(pct_annot)

print(paste(num_annot, "reads annotated of",
            num_merged, "total reads, or",
            pct_annot, "%", sep = " "))
```

```{r add new data for timepoint 1 to old}
#create "before" table for old data, new, with beta only
before = seq_annotated_megatable[time_point == 1][tx %in% c(1,2,3)]
before2 = seq_annotated_megatable2[time_point == 1][tx %in% c(1,2,3)]


both_before = rbind(before, before2, fill = TRUE)
#TDO TODO need to trim table down to smaller set of things, if I'm going to combine my timepoint, etc
both_before[,Count_both := sum(Count), by = c('prodonor_seq', 'time_point', 'tx')]

before = both_before
```



```{r segment}
#make versions of "before" data assigned to each value of rif, so i can segment on rif?
before12.5 = before
before12.5$rif = 12.5
before25 = before
before25$rif = 25
before50 = before
before50$rif = 50
before100 = before
before100$rif = 100

after = seq_annotated_megatable[(expt_set == "binary")]
after[,Count_both := Count]
before_after_1  <- rbind(before12.5, before25, before50, before100, after, fill = TRUE)
before_after_1 <- before_after_1[expt_set != "tc_2"]


#rm(before, after, before12.5, before25, before50, before100) #remove transitional tables

#while we're at it, clean up the table
before_after_1[, c("Library Id","read_id","Library Name","ssap","operation",
               "total_count",
               "bc_read",
               "options",
               "mutation",
               "barcodes",
               "drug_resistance_expected",
               "drug_sensitivity_expected"):=NULL]
```

## calculate frequency of each seq (sec count / total count)
```{r calculate frequencies}
before_after_1[, total_count_sample := sum(Count_both), by=c('time_point','tx', 'rif')]
#important: pseudocount of one given to undetected sequences AFTER calculating totals
before_after_1[Count_both == 0, Count_both := 1]

before_after_1[, seq_freq := Count_both/total_count_sample]
```
at this point, the analysis branches. here i'm examining the ratios of different alleles in rif platings of different conc, to their "initial" frequency in the t = 1 samples
 
#Rif



```{r ratio_summarize}
before_after_1[, enrichment.post.rif := seq_freq / seq_freq[time_point==1],
      by=c("tx","nickname","rif")] #within each replicate, for each sequence

into_summ = before_after_1[time_point == 3] #[Count > 5] #throwing out count filter!
binary_summ <- into_summ[,
                        list(
                          Count = mean(Count),
                          N= .N,
                          mean_seq_freq = mean(seq_freq),
                          median_seq_freq = median(seq_freq),
                          mean_enrichment = mean(enrichment.post.rif),
                          median_enrichment = median(enrichment.post.rif),
                          max_enrichment = max(enrichment.post.rif),
                          min_enrichment = min(enrichment.post.rif),
                          logmean_enrichment = 10^mean(log10(enrichment.post.rif)),
                          sd_freq = sd(seq_freq),
                          se_freq = sd(seq_freq) / sqrt(.N),
                          sd_enrichment= sd(enrichment.post.rif),
                          se_enrichment= sd(enrichment.post.rif) / sqrt(.N),
                          log_se_enrichment= 10^sd(log10(enrichment.post.rif)) / sqrt(.N)
                          ), by=c("nickname", "mut_class", "rif", "color_cat", "rpoB allele type")]

```

# plot in groups

```{r grouped_summarized, fig.width=6, fig.height=3, units='in', dpi=300}

current = binary_summ[rif == 12.5]

fig2b <- ggplot(current, aes(x=nickname, y=median_enrichment, color=mut_class, fill = mut_class)) + 
  geom_errorbar(aes(ymin=min_enrichment, ymax=max_enrichment), color="black", alpha = 0.3) +  
  geom_point(size = 2) +
  scale_y_continuous(trans = log_trans(base=10),
                     breaks = c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100),
                     labels = log10(c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100)),
                     limits=10^(c(-5.2,1.6))) +
  facet_grid(~mut_class, scales='free_x', switch='both') +
  labs(
    x = "Allele",
    y = "log10 allelic enrichment\n in 12.5 µg/mL Rifampicin",
    color = "Allele type") + 
  theme_linedraw() +
  geom_hline(yintercept=1, linetype=2) +
  theme(text = element_text(size=10)) +
  theme(
    axis.text.x= element_blank(),
    axis.ticks.x=element_blank(),
    strip.background=element_blank(), strip.placement='outside',
    strip.text=element_text(color='black'), 
    panel.spacing=unit(0,'pt'),
    panel.border=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.grid.minor.x=element_blank(),
    axis.line=element_line(),
    legend.position = 'none') +
  scale_colour_manual(name = "RpoB Allele Type",values = levels('color_cat') )

fig2b

ggsave('fig2c.pdf', plot=fig2b, width=6, height=3, units='in', dpi=300)

```


```{r plot_concentration_change, fig.width=3, fig.height=3, units='in', dpi=300}
fig2c <- ggplot(binary_summ[mut_class=='Drug_resistance'], aes(x=rif, y=median_enrichment, group=nickname)) + 
  geom_errorbar(aes(ymin=min_enrichment, ymax=max_enrichment), color="black", alpha = 0.3, width=0.03) +  
  geom_point() + geom_line() +
  scale_y_continuous(trans = log_trans(base=10),
                     breaks = c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100),
                     labels = log10(c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100)),
                     limits=10^(c(-5.2,1.6))) +
  scale_x_continuous(trans = log_trans(base=10),
                     breaks = c(12.5, 25, 50, 100)) +
  
  labs(
    x = "Rifampicin Concentration (µg/mL)",
    y = "log10 Enrichment",
    color = "Allele type") + 
  theme_linedraw() +
  geom_hline(yintercept=1, linetype=2) +
  theme(text = element_text(size=10)) +
  theme(
    strip.background=element_blank(), strip.placement='outside',
    strip.text=element_text(color='black'), 
    panel.spacing=unit(0,'pt'),
    axis.title.x=element_text(margin = margin(12,0,0,0, "pt")), 
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = 'none')

fig2c

ggsave(here::here('fig2c.pdf'), plot=fig2c, width=3, height=3, units='in', dpi=300)

```

```{r fig2bc, fig.width=6, fig.height=2, units='in', dpi=300}

relative_bc_width = 2

fig2b_comb <- fig2b + theme(plot.margin = unit(c(0, 0, 0, 0), "pt"))
fig2c_comb <- fig2c + labs(y='') + theme(plot.margin = unit(c(0, 0, 0, 0), "pt"))
grid.newpage()
fig2bc <- plot_grid(
  plotlist=list(fig2b, fig2c_comb),
  align = 'hv',
  axis='tblr',
  rel_widths = c(relative_bc_width,1))

ggsave(here::here('fig2bc.pdf'), plot=fig2bc, width=3*(relative_bc_width+1), height=3, units='in', dpi=300)


```
