---
title: "nu2E"
author: "Max Schubert"
date: "1/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(data.table)
require(scales)
library(ggpubr)
library(plotly)
#library(dplyr)

library(ggbeeswarm) #first install.packages("ggbeeswarm")

# mkdir fig_nu2E
parent_folder <- here::here('fig_nu2E')
```


```{r get_data}
data_dir = parent_folder
analysis_dir = parent_folder

#data
edit_data_name = "ZZ2_merged_bins_2"
edit_data_file = paste(data_dir, edit_data_name, sep = "/")
edit_data_dt <- data.table(fread(edit_data_file))
edit_data_melt <- melt(edit_data_dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
edit_data_melt[, uniq := str_replace_all(Sample, "_cutcount", "")]
edit_data_melt[, c("Sample","read_id") := NULL]
edit_data_melt = edit_data_melt[Count > 0] #kill zero values

```


```{r read_in_metadata}
#manifest, describing each sample sequenced
manifest_name = "k171819_liblist.csv"
manifest_file = paste(analysis_dir, manifest_name, sep = "/")
manifest_dt <- data.table(fread(manifest_file))
manifest_dt[, c("i7", "i7seq", "i5", "i5seq"):=NULL] #rm extraneous columns

#tx list, describing each transformation performed
txlist_name = "tx_list.csv"
txlist_file = paste(analysis_dir, txlist_name, sep = "/")
txlist_dt <- data.table(fread(txlist_file))

#adapters list, read in to describe ref and alt
adapters_name = "adapters_map.csv"
adapt_file = paste(analysis_dir, adapters_name, sep = "/")
adapt_dt <- data.table(fread(adapt_file))
adapt_dt[, c("5prime_cutadapt", "3prime_cutadapt", "5prime_edit", "3prime_edit"):=NULL] #rm extraneous columns

```


```{r annotate_counts}
txadapt_dt <- txlist_dt[adapt_dt, on = "locus_allele", nomatch = 0] #add "ref" and "alt" sequences expected

#merge to create metadata table
metadata <- manifest_dt[txadapt_dt, on = "tx", nomatch = 0]
metadata <- metadata[expt == "zz2_amplicons"] #rm genome experiments here
metadata[, "expt" := NULL]



#merge metadata to counts
annotated_dt <- edit_data_melt[metadata, on = "uniq", nomatch = 0]

```

#optional: clean up workspace
```{r rm}
rm("adapt_dt","adapt_file", "adapters_name", "edit_data_dt","edit_data_file",
  "edit_data_melt", "edit_data_name", "manifest_dt", "manifest_file", "manifest_name", "metadata",
  "txadapt_dt", "txlist_dt", "txlist_file", "txlist_name")
```


# measure fraction edited
```{r fraction_edited}
annotated_dt[, is_ref := (bc_read == ref)]
annotated_dt[, is_alt := (bc_read == alt)]

#of sequences matching ref or alt, what fraction is edited
#PAY ATTENTION TO THE "BY" here!!!! it's critical for assigning values to the appropriate experiments
annotated_fedit <- annotated_dt[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := 1- (Count/sum(Count)) , by='uniq'][is_ref == TRUE]
#annotated_fedit[, c("is_ref", "is_alt"):=NULL] #ditch these columns now

```

```{r keep track of reads}

total_counts_merged = sum(annotated_dt$Count)
total_counts_ref_or_alt = sum(annotated_dt[is_ref == TRUE | is_alt == TRUE]$Count)


#compare ref_alt read num to total merged
print(paste(as.character(total_counts_ref_or_alt/total_counts_merged*100), "% of reads are ref or alt seqs", sep = " "))
```

#plotting for new figure 2E
```{r set_up_plot}
mean_locus_editing = mean(fig2d_mean_editing_by_locus$mean_fraction_edited)


fig2d_rbind$locus = as.factor(fig2d_rbind$locus)
fig2d_rbind[, locus_recolor := factor(
  locus,
  levels=unique(locus)[c(4,11,1,2,3,5,6,7,8,9,10,12)])]

color_2d <- c('gyrA' = '#F8766D', 'rpoB' = '#00BFC4',
              'sucB' = '#FF64B0',
               'mreC' = '#DE8C00', 'murF' = '#00BA38', 'lolA' = '#619CFF',
               'lpxK' = '#B79F00','fabH' = '#00C08B','hemA' = '#C77CFF',
               'fliN' = '#7CAE00','hda' = '#00B4F0','coaD' = '#F564E3')

####
mean_locus_editing = mean(fig2d_mean_editing_by_locus$mean_fraction_edited)

```

## effect of optimization on efficiency
```{r h10_redo}
#temp, filter plot to look at subsets
current = annotated_fedit[locus_allele %in% c("rpoB_wide", "gyrA_ultrawide", "rpoB_plus", "gyrA_plus")]
current = current[donor_len == 90]
current = current[controltype != "offtarget_control"] 
current = current[controltype != "negative_control"]


fig_compare <- ggplot(current, aes(x= controltype, y=fraction_edited, color=locus_allele)) + 
  geom_jitter(size = 3, alpha = 0.7, stroke = 0) +
  #geom_quasirandom(method='pseudorandom', size = 3, alpha = 0.7, stroke = 0)+
  #geom_hline(yintercept=mean_locus_editing, linetype=2, size=0.5) +
  theme_linedraw() +
  #coord_cartesian(ylim=c(.5, .95)) +
  scale_y_continuous(breaks = c(.5, .6, .7, .8, .9),
                     labels = c("50%","60%", "70%", "80%", "90%")) +
  labs(
    y = "Fraction Edited") + #+
  facet_grid(~timepoint, scales = 'free_x', space = 'free_x',
             switch = 'both')  #+ #scales='free_x'
  #scale_colour_manual(values = color_2d) +
  #theme(
  #  axis.text.x = element_text(angle = 60, vjust = 1, hjust=1,
  #                             size = fig_font_size),
  #  axis.text.y = element_text(size = fig_font_size),
  #  axis.title.y = element_text(size = fig_title_font_size),
  #  axis.title.x = element_blank(),
  #  strip.background=element_blank(),
  #  panel.grid.minor=element_blank(),
  #  panel.grid.major.x=element_blank(),
  #  panel.border=element_blank(),
  #  axis.line=element_line(),
  #  legend.position = 'none')

fig_compare
```

##todo,save fig
```{r save_figure}
fig_width = 3.25
fig_height = 3.75 #edit of X,y axis makes it shorter

ggsave(here::here('fig_2D_quasi2.pdf'), plot=fig_1D, width=fig_width, 
       height=fig_height, units='in', dpi=300, device = cairo_pdf)
#ggplotly()
```
