---
title: "Fig_3C_PF020andBeta"
author: "Max Schubert"
date: "8/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(grid)
library(gridExtra)
library(cowplot)
library(here)
library(ggpubr)
library(here)

parent_folder <- here::here('fig_2cd')
source(here::here('constants.R'))
```

```{r mergebins_liblist}
mergebinpath <- paste(parent_folder,"merged_TC_march2019", sep = "/" )
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt.dt[, SampleNum := str_replace_all(Sample, "_cutcount", "")]
rm(merged_bins.dt) #remove original

#metadata
liblistpath <- paste(parent_folder,"b26_TC_metadata.csv", sep = "/" )
liblistdt <- data.table(fread(liblistpath))

#### get donors, merge to create annotated table
allelelistpath <- paste(parent_folder,"allele_annotated_list_UPDATE.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]

#merge sample and seq metadata to big table
annotated_megatable <- liblistdt[mergemelt.dt, on = "SampleNum", nomatch = 0]
rm(mergemelt.dt) #remove original, large file
seq_annotated_megatable <- annotated_megatable[seq_annot_dt, on = "bc_read", nomatch = 0]

#print statement about merge efficiency
num_merged = sum(annotated_megatable$Count)
rm(annotated_megatable) #remove original, millions of rows
num_annot = sum(seq_annotated_megatable$Count)
pct_annot = num_annot/num_merged
num_merged = as.character(num_merged)
num_annot = as.character(num_annot)
pct_annot = as.character(pct_annot)

print(paste(num_annot, "reads annotated of",
            num_merged, "total reads, or",
            pct_annot, "%", sep = " "))
```

```{r PULL_NEW_DATA}
mergebinpath2 <- paste(parent_folder,"H6_merged_bins", sep = "/" )
merged_bins2.dt <- data.table(fread(mergebinpath2))
mergemelt2.dt <- melt(merged_bins2.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt2.dt[, SampleNum := str_replace_all(Sample, "_cutcount", "")]
rm(merged_bins2.dt) #remove original

#metadata
liblistpath2 <- paste(parent_folder,"liblistH6.csv", sep = "/" )
liblistdt2 <- data.table(fread(liblistpath2))
liblistdt2[,SampleNum := as.character(SampleNum)]
#liblistdt2[,samplenum:= NULL]


allelelistpath <- paste(parent_folder,"allele_annotated_list.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]

#merge sample and seq metadata to big table
annotated_megatable2 <- liblistdt2[mergemelt2.dt, on = "SampleNum", nomatch = 0]
rm(mergemelt2.dt) #remove original, millions of rows
seq_annotated_megatable2 <- annotated_megatable2[seq_annot_dt, on = "bc_read", nomatch = 0]

#print statement about merge efficiency
num_merged = sum(annotated_megatable2$Count)
rm(annotated_megatable2) #remove original, millions of rows
num_annot = sum(seq_annotated_megatable2$Count)
pct_annot = num_annot/num_merged
num_merged = as.character(num_merged)
num_annot = as.character(num_annot)
pct_annot = as.character(pct_annot)

print(paste(num_annot, "reads annotated of",
            num_merged, "total reads, or",
            pct_annot, "%", sep = " "))
```



```{r add new data for timepoints1,2,3 to old}
#label, rbind new and old data
seq_annotated_megatable$seq_run = 1
seq_annotated_megatable2$seq_run = 2
seq_annotated_both = rbind(seq_annotated_megatable, seq_annotated_megatable2, fill = TRUE)

#filter to tc, and get rid of columns, for clarity
seq_annotated_both = seq_annotated_both[expt_set != "binary"]
seq_annotated_both[, c("Library Id","read_id","Library Name","operation",
               "total_count", "options",
               "mutation", "barcodes", "drug_resistance_expected",
               "drug_sensitivity_expected", "expt_set",
               "Sample", "wt", "altered", 
               "previous_name", "previous_category", "rpoB allele type",
               "allele_type_notes","color_cat",
               "i5_index", "i7_index", "idx1_seq","idx2_seq",
               "5prime_cutadapt"):=NULL]

#combine counts for new and old, then remove redundant rows for set 2
seq_annotated_both[,Count_both := sum(Count), by = c('tx', 'ssap', 'rif', 'time_point', 'prodonor_seq')]
seq_annotated_both = seq_annotated_both[ seq_run == 1 ]

#rename count as Count_both and get rid of old columns
seq_annotated_both[, count := Count_both]
seq_annotated_both[, c("Count","Count_both"):=NULL]

```


```{r calculate frequencies and normalize}
## calculate frequency of each seq (sec count / total count)
seq_annotated_both[, total_count_sample := sum(count), by=c('time_point','tx')]
#pseudocount of one given to undetected sequences AFTER calculating totals:
seq_annotated_both[count == 0, count := 1]
seq_annotated_both[, seq_freq := count/total_count_sample]

#calculate mean of neutral controls, ratio of each to this, also try sum of all neutrals
seq_annotated_both[, mean_neutrals := mean(count[mut_class == "Neutral"]), by = c('time_point','tx')]
seq_annotated_both[, median_neutrals := median(as.numeric(count[mut_class == "Neutral"])),
                   by=c('time_point','tx')]
seq_annotated_both[, ratio_mean_neutrals := count/mean_neutrals]
seq_annotated_both[, ratio_median_neutrals := count/median_neutrals]


#seq_annotated_both[, ratio_median_neutrals_by := count/median_neutrals, by='bc_read']
#before_after_1[, enrichment.post.rif := seq_freq / seq_freq[time_point==1],
#      by=c("tx","nickname","rif")] #within each replicate, for each sequence

```

```{r summarize}
#into_summ = before_after_1[time_point == 3] #[Count > 5] #throwing out count filter!

tc_summ <- seq_annotated_both[,
                        list(
                          mean_count = mean(count),
                          N= .N,
                          mean_seq_freq = mean(seq_freq),
                          mean_ratio_mean_neutrals = mean(ratio_mean_neutrals),
                          mean_ratio_median_neutrals = mean(ratio_median_neutrals),
                          logmean_ratio_mean_neutrals = 10^mean(log10(ratio_mean_neutrals)),
                          se_ratio_mean_neutrals = sd(ratio_mean_neutrals) / sqrt(.N),
                          se_ratio_median_neutrals = sd(ratio_median_neutrals) / sqrt(.N),
                          log_se_ratio_mean_neutrals= 10^sd(log10(ratio_mean_neutrals)) / sqrt(.N)
                          ), by=c("nickname", "mut_class", "rif",
                                  'time_point', 'ssap', 'mfe')]

```
```{r plot}
tc_summ_rif5 <- tc_summ[rif == 5][ssap == 'PF020']
tc_summ_rif0 <- tc_summ[rif == 0][ssap == 'PF020']

ggplot(tc_summ_rif0, aes(x=mean_ratio_median_neutrals, y=mean_ratio_median_neutrals_by,
                         color=mut_class, group = interaction(nickname, ssap))) + 
  #geom_errorbar(aes(ymin=mean_ratio_mean_neutrals-se_ratio_mean_neutrals,
  #                  ymax=mean_ratio_mean_neutrals+se_ratio_mean_neutrals,
  #                  alpha = .3), width=.1) +
  geom_line(aes(alpha = .3)) +
  geom_point(aes(group = nickname, alpha = .3)) +
  scale_y_continuous(trans = log10_trans(), #limit=c(0.0005, 8), 
                     breaks = c(.0001, .001, .01, .1, 1, 10, 100, 1000, 10000, 100000, 1000000)) +
  theme_bw() +
  facet_wrap(~mut_class)+
  theme(legend.position="none")
```



#fig2 plotting statements...

# plot in groups
```{r grouped_summarized, fig.width=6, fig.height=3, units='in', dpi=300}

color_vals = c('grey44','darkorange3','darkorange2','darkorange')

addline_format <- function(x,...){gsub(' ','\n',x)}


current = binary_summ[rif == 12.5]
current[, mut_class := factor(
  mut_class,
  levels=unique(mut_class)[c(2,1,3,4,5)],
  labels=addline_format(unique(mut_class)[c(2,1,3,4,5)]))]


fig2b <- ggplot(tc_summ, aes(x=nickname, y=median_enrichment, color=as.factor(color_cat), fill = as.factor(color_cat))) + 
  geom_errorbar(aes(ymin=min_enrichment, ymax=max_enrichment), color="black", alpha = 0.3) +  
  geom_point(size = 2) +
  scale_y_continuous(trans = log_trans(base=10),
                     breaks = c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100),
                     labels = log10(c(.000001, .00001, .0001, .001, .01, .1, 1, 10, 100)),
                     limits=10^(c(-5.2,1.6))) +
  scale_x_discrete(expand=c(0.16,0.16)) +
  facet_grid(~mut_class, scales='free_x', switch='both') +
  labs(
    x = "Allele",
    y = "Allelic enrichment, (log10)\n 12.5 µg/mL Rifampicin",
    color = "Allele type") + 
  theme_linedraw() +
  geom_hline(yintercept=1, linetype=2) +
  theme(text = element_text(size=fig_font_size)) +
  theme(
    axis.text.x= element_blank(),
    axis.ticks.x=element_blank(),
    strip.background=element_blank(), strip.placement='outside',
    strip.text=element_text(color='black'), 
    panel.spacing=unit(0,'pt'),
    panel.border=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.grid.minor.x=element_blank(),
    axis.line=element_line(),
    legend.position = 'none') +
  scale_colour_manual(name = "RpoB Allele Type", values = color_vals)

fig2b

#ggsave('fig2c.pdf', plot=fig2b, width=6, height=3, units='in', dpi=300)

```
