---
title: "Fig_4B"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(gridExtra)
library(here)
library(ggpubr)
library(here)

parent_folder <- here::here('fig_4B')
source(here::here('constants.R'))

```
```{r get data}
#this is the file with minimum counts 20
mergebinpath <- paste(parent_folder,"7_18_merged_bins", sep = "/" )
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt.dt[, unique_id := str_replace_all(Sample, "_cutcount", "")]

```

```{r sample metadata}
#import library annotations, trim some extraneous columns, trim some extraneous rows
liblistpath <- paste(parent_folder,"lib_list.csv", sep = "/" )
liblistdt <- data.table(fread(liblistpath))

liblistdt[, c("Indices",
              "Expected Percent of Pool",
              "File Name",
              "PF Reads",
              "%mergepass",
              "galK_strain",
              "galK_construct"):=NULL]

liblistdt <-liblistdt[ratio_expt != "prev", ]
liblistdt <-liblistdt[ratio_expt != "galk", ]

annotated_megatable <- liblistdt[mergemelt.dt, on = "unique_id", nomatch = 0]

```

```{r sequence metadata}
#read in donor annotations, rename seq to bc_read, merge annotations
allelelistpath <- paste(parent_folder,"allele_annotated_list_UPDATE.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]
#merge these annotations to big table
seq_annotated_megatable <- annotated_megatable[seq_annot_dt, on = "bc_read", nomatch = 0]
```

```{r normalization}
#calculate mean of neutral controls, ratio of each to this
megatable_ratios <- seq_annotated_megatable[, mean_neutrals := mean(Count[mut_class == "Neutral"]), by='unique_id']
megatable_ratios <- seq_annotated_megatable[, median_neutrals := median(Count[mut_class == "Neutral"]), by='unique_id']

megatable_ratios <- megatable_ratios[, ratio_to_neutrals := Count/median_neutrals, by='bc_read'] #threw away included filter by count statement...

#calculate fraction (useful for rif100)
megatable_ratios <- megatable_ratios[, total_count_uniqid := Count, by='unique_id']
megatable_ratios <- megatable_ratios[, frac.tot := Count/total_count_uniqid, by='bc_read'] #threw away included filter by count statement...

seq_annotated_megatable <- megatable_ratios

####normalize values to expression at t= 1
#first, fix the issue with A, A5, etc by making two tables
a5mega <- seq_annotated_megatable[ratio_expt == 'A'][, ratio_expt := 'A_5'][sample_type != 'msDNA' & replicate != 'D']
a100mega <- seq_annotated_megatable[timepoint %in% c(0, 1) & ratio_expt == 'A'][, ratio_expt := 'A_100'][sample_type == 'plasmid' & replicate != 'D']
restofitA5 <-  seq_annotated_megatable[timepoint %in% c(2, 3) & ratio_expt == 'A_5']
restofitA100 <-  seq_annotated_megatable[timepoint %in% c(2, 3) & ratio_expt == 'A_100']
megatable5 <- rbind(a5mega, restofitA5)
megatable100 <- rbind(a100mega, restofitA100)

megatable5[, read.pct := Count/sum(Count), by=c('timepoint','replicate')]

megatable5[,
           plas.enrichment := ratio_to_neutrals / ratio_to_neutrals[timepoint==-1],
           by=c("nickname", "mut_class")]

```


#figure 4B
##staging for figure:
```{r fig_4B, fig.height=5, fig.width=4, dpi=300}
summary <- megatable5[, 
  list(
    read.pct = mean(read.pct),
    N= .N,
    plas.enrichment= mean(plas.enrichment),
    sd= sd(plas.enrichment),
    se= sd(plas.enrichment) / sqrt(.N)),
  by=c( "timepoint", "sample_type", "induction", "prodonor_seq", "nickname", "mut_class")]

summary <- summary[sample_type != "msDNA" & mut_class %in% c('Lethal','Neutral','rpoB Alleles')]
summary[, mut_class := factor(mut_class, levels=c('rpoB Alleles', 'Neutral',  'Lethal'))]

categories_to_plot <- c('Lethal','Neutral','rpoB Alleles')
condition_labels <- c(
  'Plasmid\nLibrary',
  'Transformed',
  'Induced',
  '20 generations\n+Rif',
  '40 generations\n+Rif')

squish_predrug_x <- 0.4
summary[, timepoint := as.numeric(timepoint)]
summary[timepoint == -1, timepoint := 1-squish_predrug_x*2]
summary[timepoint == 0, timepoint := 1-squish_predrug_x]
```
```{r plot_4B}
fig4B <- ggplot(summary,
    aes(x=timepoint, y=plas.enrichment, color=mut_class, group=nickname)) + 
  geom_hline(yintercept=0, color='black', size=1) +
  geom_vline(xintercept=-Inf, color='black', size=1) +
  annotate('rect', ymin=0, ymax=Inf, xmin=-Inf, xmax=1.05, fill='black', alpha=0.1, color=NA) +
  geom_line(show.legend = FALSE) +
  geom_errorbar(aes(ymin=plas.enrichment-se, ymax=plas.enrichment+se),
    show.legend = FALSE, color='black', alpha=0.3, width=0.05) +
  geom_point(aes(group = nickname),show.legend = FALSE) +
  scale_y_continuous(trans = log10_trans(),
                     breaks = c(.3, 1, 3, 10, 100, 1000, 10000), 
                     labels = c("0.3", "1", "3", "10", "100", "1,000", "10,000")) +
  scale_x_continuous(labels=condition_labels, breaks=summary[, unique(timepoint)], expand=c(0,0.3)) +
  labs(y='Allelic enrichment', x='') +
  facet_grid(mut_class~., space='free_y', scales='free_y', switch='both') +
  annotation_logticks(sides = "l") +
  theme_linedraw() +
  geom_hline(yintercept=1, linetype=2, size=0.5) +
  theme(
    strip.background=element_blank(), strip.placement='outside',
    panel.spacing=unit(12,'pt'),
    panel.border=element_blank(),
    panel.grid.minor.x=element_blank(),
    axis.line.y=element_blank(),
    axis.line.x=element_blank(),
    legend.position = 'none',
    axis.text.x = element_text(size = fig_font_size), #fix text sizes
    axis.text.y = element_text(size = fig_font_size),
    axis.title.y = element_text(size = fig_title_font_size),
    axis.title.x = element_blank(),
    strip.text=element_text(color='black',
                            margin = margin(0,0,0,16, "pt"),
                            size = fig_font_size))

fig4B
```

```{r save_4B}
ggsave(here::here('fig_4B_real.pdf'), plot=fig4B, width=4, height=4, units='in', dpi=300, device = cairo_pdf)

#save data
save('megatable5', file=here::here('fig_4B_real','fig4Bdata_megatable5.RData'))
save('megatable100', file=here::here('fig_4B_real','fig4Bdata_megatable100.RData'))
```


