---
title: "Fig_3d_linmodel"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)

parent_folder = here::here('fig_3d')

```

```{r get data}
#get RLR trajectory data
lin.mod.path = parent_folder
start.data.file = paste(here::here('fig_3b'), "fig3bdata.RData", sep = "/")
load(start.data.file) #this creates the file megatable5

#get clonal growth data
clonal_growth_path = paste(parent_folder, 'summary3C.csv', sep = "/")
clonalgrowth.dt = data.table(fread(clonal_growth_path))
```

```{r summarize, fit}
#prepare summary table with stats per donor per sample, NOT per replicate

megatable5[,
           ratio_median_neutrals := ratio_to_neutrals, #/ ratio_to_neutrals[timepoint==1],
           by=c("nickname", "mut_class","replicate")]

summary <- megatable5[, 
                            list(
                              Count = Count,
                              N= .N,
                              meanRatio= mean(ratio_median_neutrals),
                              sd= sd(ratio_median_neutrals),
                              se= sd(ratio_median_neutrals) / sqrt(.N)),
                            by=c("ratio_expt", "timepoint", "sample_type", "induction", "bc_read", "nickname", "mut_class")]

lm_group <- function(dt_subset, byval) {
  lmod <- lm(log10(ratio_median_neutrals) ~ timepoint, data= dt_subset[is.finite(ratio_median_neutrals)])
  return(list(intercept= lmod$coefficients[1], slope= lmod$coefficients[2], mut_class= dt_subset$mut_class[1]))
}

megatable_slopes <- megatable5[
  (ratio_expt == "A" | ratio_expt == "A_5") & (ratio_median_neutrals > 0) &
    (timepoint %in% c(1,2)) & 
    sample_type != 'msDNA' & induction != 'n',
  lm_group(.SD,.BY),
  by='nickname']

```

```{r plot_linmodel}
summary <- summary[ratio_expt == "A" | ratio_expt == "A_5", ] #looking at rif5
summary <- summary[timepoint != "-1", ]
summary <- summary[timepoint != "0", ]
summary <- summary[sample_type != "msDNA", ]
summary <- summary[induction != "n", ]

ggplot(summary, aes(x=timepoint, y=log10(meanRatio), color=nickname)) + 
  geom_errorbar(aes(ymin=log10(meanRatio-se), ymax=log10(meanRatio+se)), width=.1, show.legend = FALSE) +
  geom_line(show.legend = FALSE) +
  geom_point(aes(group = nickname),show.legend = FALSE) +
  scale_y_continuous(labels = c(.001, .01, .1, 1, 10, 100), breaks=log10(c(.001, .01, .1, 1, 10, 100))) +
  theme_bw() +
  geom_abline(show.legend = FALSE, data=megatable_slopes, aes(intercept=intercept, slope=slope, color=nickname), linetype=2) +
  facet_wrap(~mut_class)
```


```{r look_at_fewer}
simple_summ <- summary[mut_class %in% c('Lethal','Neutral','rpoB Alleles')]
simple_slopes <- megatable_slopes[mut_class %in% c('Lethal','Neutral','rpoB Alleles')]

#write_path = "/Users/Max_Schubert/Dropbox/RLR_e.coli_dropbox/NewNotebook_expts/A_phenotype_in_plates/a27_more_points"
#write.csv(simple_slopes, paste(write_path, 'simple_slopes.csv', sep = "/"))

ggplot(simple_summ, aes(x=timepoint, y=log10(meanRatio), color=nickname)) + 
  geom_errorbar(aes(ymin=log10(meanRatio-se), ymax=log10(meanRatio+se)), width=.1, show.legend = FALSE) +
  geom_line(show.legend = FALSE) +
  geom_point(aes(group = nickname),show.legend = FALSE) +
  scale_y_continuous(labels = c(.001, .01, .1, 1, 10, 100), breaks=log10(c(.001, .01, .1, 1, 10, 100))) +
  theme_bw() +
  geom_abline(show.legend = FALSE, data=simple_slopes, aes(intercept=intercept, slope=slope, color=nickname), 
    linetype=2) +
  facet_wrap(~mut_class)
```

#### summary plot for slopes???
```{r plot slopes by mut class}
#try comparison of ALL control alleles to lethals
#mutate_slopes <- megatable_slopes[!mut_class %in% c('Lethal', 'rpoB Alleles'), mut_class := "Control set"]
#comparisons = list(c('Lethal','Control set'))

ggplot(simple_slopes, aes(x=mut_class, y=slope, group = nickname, color = mut_class))+
  geom_point()+
  theme_bw() +
  stat_compare_means(comparisons = list(c('Lethal','Neutral'))) #+
  #scale_y_continuous(trans = log10_trans())
```




```{r 3d, fig.height=5, fig.width=4, dpi=300}

# dirty fix to harmonize allele names
simple_slopes[nickname=='rpoB_CACTCGGCCCAG_1595_nan', nickname := 'rpoB_CACTCGGCCCAG_1594_nan']
simple_slopes[nickname=='rpoB_C_1534_T', nickname := 'rpoB_C_1535_T']
# add wildtype to slopes explicitly
simple_slopes_final <- rbind(simple_slopes, data.table(nickname='WT', intercept=0, slope=0, mut_class='Neutral'))

indiv_v_rlr <- merge(clonalgrowth.dt, simple_slopes_final, by.x='hard_desc', by.y='nickname')

#slope_fit <- indiv_v_rlr[, cor.test(slope, mean-1, method=c("pearson"))]
slope_fit <- indiv_v_rlr[, cor.test(slope, log10(mean), method=c("pearson"))]
#slope_fit <- indiv_v_rlr[, cor.test(2^slope, mean, method=c("pearson"))]

p.val <- format(slope_fit$p.value, scientific=TRUE, digits=3)
pearson_r <- round(slope_fit$estimate, 3)

fig_3d <- ggplot(indiv_v_rlr, 
  aes(x=slope, y=log10(mean))) + 
  #aes(x=slope, y=mean, ymin=mean-se, ymax=mean+se)) + 
  geom_point() + 
  geom_errorbar(width=0.05, ymin=log10(mean-se), ymax=log10(mean+se)) +
  labs(x='RLR relative enrichment (rel. to WT)', y='clonally measured log(µ) (rel to. WT)') +
  stat_smooth(method = "lm", col = "red", se=FALSE) +
  annotate(geom='text', label=paste0('r = ',pearson_r,'\n','p=',p.val), y=0.2, x=0.25) +
  theme(text = element_text(size=10))

fig_3d

#ggsave(here::here('fig_3d.pdf'), plot=fig_3d, width=3, height=3, units='in', dpi=300, useDingbats=FALSE)

```


#######
### try more stuff with linmod

```{r max_trying things}

megatable_slopes_3points <- megatable5[
  (ratio_expt == "A" | ratio_expt == "A_5") & (ratio_median_neutrals > 0) &
    (timepoint %in% c(1,2,3)) & 
    sample_type != 'msDNA' & induction != 'n',
  lm_group(.SD,.BY),
  by='nickname']
simple_slopes3 <- megatable_slopes_3points[mut_class %in% c('Lethal','Neutral','rpoB Alleles')]

#
# dirty fix to harmonize allele names
simple_slopes3[nickname=='rpoB_CACTCGGCCCAG_1595_nan', nickname := 'rpoB_CACTCGGCCCAG_1594_nan']
simple_slopes3[nickname=='rpoB_C_1534_T', nickname := 'rpoB_C_1535_T']
# add wildtype to slopes explicitly
simple_slopes_final3 <- rbind(simple_slopes3, data.table(nickname='WT', intercept=0, slope=0, mut_class='Neutral'))

indiv_v_rlr3 <- merge(clonalgrowth.dt, simple_slopes_final3, by.x='hard_desc', by.y='nickname')

#slope_fit <- indiv_v_rlr[, cor.test(slope, mean-1, method=c("pearson"))]
slope_fit3 <- indiv_v_rlr3[, cor.test(slope, log10(mean), method=c("pearson"))]
#slope_fit <- indiv_v_rlr[, cor.test(2^slope, mean, method=c("pearson"))]

p.val <- format(slope_fit3$p.value, scientific=TRUE, digits=3)
pearson_r <- round(slope_fit3$estimate, 3)
#

fig_3d <- ggplot(indiv_v_rlr3, 
  aes(x=slope, y=log10(mean))) + 
  #aes(x=slope, y=mean, ymin=mean-se, ymax=mean+se)) + 
  geom_point() + 
  geom_errorbar(width=0.05, aes(ymin=log10(mean-se), ymax=log10(mean+se))) +
  labs(x='RLR relative enrichment (rel. to WT)', y='clonally measured log(µ) (rel to. WT)') +
  stat_smooth(method = "lm", col = "red", se=FALSE) +
  annotate(geom='text', label=paste0('r = ',pearson_r,'\n','p=',p.val), y=0.2, x=0.25) +
  theme(text = element_text(size=10))

fig_3d

##############
##### try all replicates having their own linmod
megatable_slopes_3points_3reps <- megatable5[
  (ratio_expt == "A" | ratio_expt == "A_5") & (ratio_median_neutrals > 0) &
    (timepoint %in% c(1,2,3)) & 
    sample_type != 'msDNA' & induction != 'n',
  lm_group(.SD,.BY),
  by=c('nickname', 'replicate')]


simple_slopes_allreps <- megatable_slopes_3points_3reps[mut_class %in% c('Lethal','Neutral','rpoB Alleles')]


simpleslopesumm <- simple_slopes_allreps[, 
                            list(
                              N= .N,
                              meanSlope= mean(slope),
                              slope_sd= sd(slope),
                              slope_se= sd(slope) / sqrt(.N)),
                            by=c("nickname", "mut_class")]

ggplot(simple_slopes_allreps, aes(x=mut_class, y=slope, group = interaction(nickname, replicate), color = mut_class))+
  geom_point()+
  theme_bw() +
  stat_compare_means(comparisons = list(c('Lethal','Neutral')), test = t.test)
```



