---
title: "Fig_3B"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(gridExtra)
library(here)
library(ggpubr)
library(here)

parent_folder <- here::here('fig_3b')

```
```{r get data}
#parent_folder <- "/Users/Max_Schubert/Dropbox (Personal)/RLR_e.coli_dropbox/NewNotebook_expts/A_phenotype_in_plates/ms23_testset_primerize"

#this is the file with minimum counts 20
mergebinpath <- paste(parent_folder,"7_18_merged_bins", sep = "/" )
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
mergemelt.dt[, unique_id := str_replace_all(Sample, "_cutcount", "")]

```

```{r sample metadata}
#import library annotations, trim some extraneous columns, trim some extraneous rows
liblistpath <- paste(parent_folder,"lib_list.csv", sep = "/" )
liblistdt <- data.table(fread(liblistpath))

liblistdt[, c("Indices",
              "Expected Percent of Pool",
              "File Name",
              "PF Reads",
              "%mergepass",
              "galK_strain",
              "galK_construct"):=NULL]

liblistdt <-liblistdt[ratio_expt != "prev", ]
liblistdt <-liblistdt[ratio_expt != "galk", ]

annotated_megatable <- liblistdt[mergemelt.dt, on = "unique_id", nomatch = 0]

```

```{r sequence metadata}
#read in donor annotations, rename seq to bc_read, merge annotations
allelelistpath <- paste(parent_folder,"allele_annotated_list.csv", sep = "/" )
seq_annot_dt <- data.table(fread(allelelistpath))
seq_annot_dt[, bc_read := prodonor_seq]
#merge these annotations to big table
seq_annotated_megatable <- annotated_megatable[seq_annot_dt, on = "bc_read", nomatch = 0]
```

```{r normalization}
#calculate mean of neutral controls, ratio of each to this
megatable_ratios <- seq_annotated_megatable[, mean_neutrals := mean(Count[mut_class == "Neutral"]), by='unique_id']
megatable_ratios <- megatable_ratios[, ratio_to_neutrals := Count/mean_neutrals, by='bc_read'] #threw away included filter by count statement...

#calculate fraction (useful for rif100, where shit dies)
megatable_ratios <- megatable_ratios[, total_count_uniqid := Count, by='unique_id']
megatable_ratios <- megatable_ratios[, frac.tot := Count/total_count_uniqid, by='bc_read'] #threw away included filter by count statement...

#spoof to change name 
seq_annotated_megatable <- megatable_ratios

####normalize values to expression at t= 1
#first, fix the issue with A, A5, etc by making two tables
a5mega <- seq_annotated_megatable[timepoint %in% c(0, 1) & ratio_expt == 'A'][, ratio_expt := 'A_5'][sample_type == 'plasmid' & replicate != 'D']
a100mega <- seq_annotated_megatable[timepoint %in% c(0, 1) & ratio_expt == 'A'][, ratio_expt := 'A_100'][sample_type == 'plasmid' & replicate != 'D']
restofitA5 <-  seq_annotated_megatable[timepoint %in% c(2, 3) & ratio_expt == 'A_5']
restofitA100 <-  seq_annotated_megatable[timepoint %in% c(2, 3) & ratio_expt == 'A_100']
megatable5 <- rbind(a5mega, restofitA5)
megatable100 <- rbind(a100mega, restofitA100)

#next, establish "enrichment" as it's abundance, relative to t=1
megatable5[,
           t1.enrichment := ratio_to_neutrals / ratio_to_neutrals[timepoint==1],
           by=c("nickname", "mut_class", "replicate")]
megatable100[,
             t1.enrichment := ratio_to_neutrals / ratio_to_neutrals[timepoint==1],
             by=c("nickname", "mut_class", "replicate")]

#next, try out a summary stat, timepoint 3/2
#megatable5[,
#           three.over.two := t1.enrichment[timepoint==3] / #t1.enrichment[timepoint==2],
#           by=c("nickname", "mut_class", "replicate")]

#now burn ratio_expt, and other columns that aren't relevant
megatable5[, c("unique_id",
               "Name",
               "Sample",
               "ratio_expt",
               "exprs_expt",
               "V17",
               "V18",
               "read_id",
               "total_count",
               "bc_read",
               "i.Sample",
               "options",
               "mutation",
               "barcodes"):=NULL]

megatable100[, c("unique_id",
                 "Name",
                 "Sample",
                 "ratio_expt",
                 "exprs_expt",
                 "read_id",
                 "total_count",
                 "bc_read",
                 "i.Sample",
                 "options",
                 "mutation",
                 "barcodes"):=NULL]

```

```{r plot_rif_100}
currenttable = megatable100 #set experiment to view

#define means
summary <- currenttable[,
                        list(
                          Count = Count,
                          N= .N,
                          meanRatio= mean(t1.enrichment),
                          sd= sd(t1.enrichment),
                          se= sd(t1.enrichment) / sqrt(.N)),
                        by=c("nickname", "mut_class", "timepoint")]



ggplot(summary, aes(x=timepoint, y=meanRatio, color=nickname)) + 
  geom_errorbar(aes(ymin=meanRatio-se, ymax=meanRatio+se, alpha = .3), width=.1) +
  geom_line(aes(alpha = .3)) +
  geom_point(aes(group = nickname, alpha = .3)) +
  scale_y_continuous(trans = log10_trans(), #limit=c(0.0005, 8), 
                     breaks = c(.0001, .001, .01, .1, 1, 10, 100, 1000, 10000)) +
  theme_bw() +
  facet_wrap(~mut_class) +
  theme(legend.position="none")

```

```{r plot_rif5}
summary <- megatable_ratios[, 
                                        list(
                                          Count = Count,
                                          N= .N,
                                          meanRatio= mean(ratio_to_neutrals),
                                          sd= sd(ratio_to_neutrals),
                                          se= sd(ratio_to_neutrals) / sqrt(.N)),
                                        by=c("ratio_expt", "timepoint", "sample_type", "induction", "bc_read", "nickname", "mut_class")]



####_________________
#examine rif5 experiment
summary <- summary[ratio_expt == "A" | ratio_expt == "A_5", ] #testing rif100 verson
summary <- summary[timepoint != "-1", ]
summary <- summary[timepoint != "0", ]
summary <- summary[sample_type != "msDNA", ]

ggplot(summary, aes(x=timepoint, y=meanRatio, color=nickname)) + 
  geom_errorbar(aes(ymin=meanRatio-se, ymax=meanRatio+se), width=.1, show.legend = FALSE) +
  geom_line(show.legend = FALSE) +
  geom_point(aes(group = nickname),show.legend = FALSE) +
  scale_y_continuous(trans = log10_trans(), #limit=c(0.0005, 8), 
                     breaks = c(.001, .01, .1, 1, 10, 100)) +
  #theme(legend.position="none") +
  theme_bw() +
  facet_wrap(~mut_class)


```


