---
title: "fig_2C_S1D_S2A"
author: "Max Schubert"
date: "1/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
require(ggplot2)
require(data.table)
require(scales)

parent_folder <- here::here('fig_2C_S1D_S2A')

source(here::here('constants.R'))
```

#get data for simulation, and edited fractions from figure 2D
```{r get_data}
#simulation data
sim_data_path = paste(parent_folder, "neutral_editing.csv", sep = "/")
sim_data = data.table(fread(sim_data_path))

#editing data
edit_data_path = paste(parent_folder, "2D_summ.rds", sep = "/")
edit_data = readRDS(edit_data_path)
edit_data$growth = "Batch"
```

#get data from continuous editing in a turbidostat
```{r get_data}
#this is the file with minimum counts 20
mergebinpath <- paste(parent_folder, "ev1_edit_merged_bins", sep = "/")
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')

mergemelt.dt[, sample_ID := str_replace_all(Sample, "_cutcount", "")]

#import library annotations, trim some extraneous columns, trim some extraneous rows
liblistpath <- paste(parent_folder, "lib_list.csv", sep = "/")
liblistdt <- data.table(fread(liblistpath))

liblistdt[, c("id",
              "column",
              "row"):=NULL]

annotated_megatable <- liblistdt[mergemelt.dt, on = "sample_ID", nomatch = 0]

#load table of timepoint ~ hours, merge hours to current table
hours_path <-  paste(parent_folder, "timepoint_hours.csv", sep = "/")
hours.dt <- data.table(fread(hours_path))
annotated_megatable_hours <- annotated_megatable[hours.dt, on = "timepoint", nomatch = 0]


#read in edit seqs (ref, alt)
refaltpath <- paste(parent_folder, "adapters_map.csv", sep = "/")
refalt_dt <- data.table(fread(refaltpath))

refalt_dt[, c("5prime_cutadapt",
              "3prime_cutadapt",
              "5prime_edit",
              "3prime_edit"):=NULL]
#merge ref and alt to table
#for now, using expt_set, though in the future something more complex should be used
seq_annotated_megatable <- annotated_megatable_hours[refalt_dt, on = "expt_set", nomatch = 0]

```

```{r calc_editing}
#establishes control sample and normalizes to this, prints into "ratio", kill singletons
seq_annotated_megatable[, is_ref := (bc_read == ref)]
seq_annotated_megatable[, is_alt := (bc_read == alt)]

edited_fractions_ev <- seq_annotated_megatable[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := 1- (Count/sum(Count)) , by='Sample'][is_ref == TRUE]

#filter to relevant experiment, remove extraneous rows for this analysis
edited_fractions_ev <- edited_fractions_ev[expt_set == "ev_gyr"]
edited_fractions_ev_filter <-  edited_fractions_ev[,c("ev_vial", "timepoint", "fraction_edited", "hours")]
```

```{r more_turbidostat_data_cleaning}
#set metadata, assuming that 1 hour == 1 gen #todo, improve on this
edited_fractions_ev_filter$generations = edited_fractions_ev_filter$hours #todo
edited_fractions_ev_filter$growth = "Turbidostat"
edited_fractions_ev_filter$locus = "gyrA"
edited_fractions_ev_filter_xx = edited_fractions_ev_filter[ev_vial == "xx"] #shared initial time point
edited_fractions_ev_filter = edited_fractions_ev_filter[ev_vial != "xx"] #rm from shared table

#create replicate initial values for all vials
edited_fractions_ev_filter_xx3 = edited_fractions_ev_filter_xx
edited_fractions_ev_filter_xx3$ev_vial = 3
edited_fractions_ev_filter_xx7 = edited_fractions_ev_filter_xx
edited_fractions_ev_filter_xx7$ev_vial = 7
edited_fractions_ev_filter_xx11 = edited_fractions_ev_filter_xx
edited_fractions_ev_filter_xx11$ev_vial = 11
edited_fractions_ev_filter_xx15 = edited_fractions_ev_filter_xx
edited_fractions_ev_filter_xx15$ev_vial = 15

edited_fractions_ev_tidy = rbind(edited_fractions_ev_filter_xx3, edited_fractions_ev_filter_xx7, edited_fractions_ev_filter_xx11, edited_fractions_ev_filter_xx15, edited_fractions_ev_filter)

#print turbidostat editing table
output_to = paste(parent_folder, 'turbidostat_editing_summary.csv', sep = "/")
fwrite(edited_fractions_ev_tidy,output_to)

#load version with manually annotated generations from gens_table files
read_from = paste(parent_folder, 'turbidostat_editing_summary_annotated.csv', sep = "/")
edited_fractions_ev_tidy_annotated = fread(read_from)
```


#plot 2E
```{r setup_plot}
#mean_locus_editing colors
color_2d <- c('gyrA' = '#F8766D', 'rpoB' = '#00B4F0',
              'sucB' = '#FF64B0',
              'mreC' = '#DE8C00', 'murF' = '#00BA38', 'lolA' = '#619CFF',
              'lpxK' = '#B79F00','fabH' = '#00C08B','hemA' = '#C77CFF',
              'fliN' = '#7CAE00','hda' = '#00BFC4','coaD' = '#F564E3',
              '0.05' = "#DCDCDC", '0.07' = "#808080",
              '0.09'= "#708090", '0.11' = "#000000")


#specify shapes
shape_palette = c('Batch' = 16, 'Turbidostat' = 17)
```




```{r execute_plot}
fig_2E <- ggplot(NULL) + 
  geom_line(data = sim_data, aes(x=generations, y=fraction_edited,
                group = as.factor(r), color = as.factor(r))) +
  geom_point(data = edit_data,
             aes(x= 20, y = mean_fraction_edited,
                 group = locus, color = locus, shape = growth),
             size = 3, alpha = 0.7, stroke = 0) +
  scale_color_manual(values = color_2d) +
  #scale_shape_manual(values = shape_palette) +
  theme_linedraw() +
  scale_y_continuous(breaks = c(0, .25, .5, .75, 1),
                     labels = c("0%","25%", "50%", "75%", "100%"),
                     limits = c(0, 1)) +
  scale_x_continuous(breaks = c(0, 10, 20,30),
                     limits = c(0,30)) +
  labs(
    y = "Fraction Edited",
    x = "Generations") +
  theme(
    axis.text.x = element_text(size = fig_font_size),
    axis.text.y = element_text(size = fig_font_size),
    axis.title.y = element_blank(),
    axis.title.x = element_text(size = fig_title_font_size),
    strip.background=element_blank(),
    panel.grid.minor=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = "none")

fig_2E

```

```{r save_plot}
fig_width=2.5
fig_height = 3.33

ggsave(here::here('fig_2E_out.pdf'), plot=fig_2C,
       width=fig_width, height=fig_height,
       units='in', dpi=300, device = cairo_pdf)
```


#figure S5B, turbidostat results in hours
##### moving this to supplemental
```{r examine_turbidostat_data_hours}
figS5B <- ggplot(NULL)+
  geom_line(data = edited_fractions_ev_tidy_annotated,
            aes(x = hours, y= fraction_edited,
                 color = '#F8766D', group = ev_vial),
            size = 1, alpha = 0.5) +
  geom_point(data = edited_fractions_ev_tidy_annotated,
             aes(x = hours, y= fraction_edited,
                 color = '#F8766D', group = ev_vial),
             size =3, alpha = 0.8) +
  theme_linedraw() +
  scale_y_continuous(breaks = c(0, .25, .5, .75, 1),
                     labels = c("0%","25%", "50%", "75%", "100%")) +
  scale_x_continuous(breaks = c(0, 24, 48, 72),
                     limits = c(0,73)) +
  labs(
    y = "Fraction Edited",
    x = "Hours") +
  theme(
    axis.text.x = element_text(size = fig_font_size),
    axis.text.y = element_text(size = fig_font_size),
    axis.title.y = element_text(size = fig_title_font_size),
    axis.title.x = element_text(size = fig_title_font_size),
    strip.background=element_blank(),
    panel.grid.minor=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = "none")

figS5B

```
```{r save_1C}
ggsave(here::here('fig_S5B.pdf'), plot=figS5B,
       width=2.5, height=3.3,
       units='in', dpi=300, device = cairo_pdf)

```

####optional: view different vials by shape
#figure 2C
##new version, separating vials with shape
```{r examine_turbidostat_data_with_generations}
color_set = c('observed' = '#F8766D', "simulated" =  "#000000")
sim_data$color = "simulated"
edited_fractions_ev_tidy_annotated$color = 'observed'

shape_set = c("3" = 15, "7" = 16,
                 "11"= 17, "15" = 18)


fig_2C <- ggplot(NULL)+
  geom_line(data = sim_data[r == 0.05],
            aes(x = generations, y= fraction_edited,
                 color = color), size = 1, alpha = 0.7, linetype = "dashed") +
  geom_point(data = edited_fractions_ev_tidy_annotated,
             aes(x = generations_annotated, y= fraction_edited,
                 color = color, shape = as.factor(ev_vial)),
             size = 3, alpha = 0.8, stroke = 1) +
  
  theme_linedraw() +
  scale_y_continuous(breaks = c(0, .25, .5, .75, 1),
                     labels = c("0%","25%", "50%", "75%", "100%")) +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80, 100)) +
  scale_color_manual(values = color_set) +
  scale_shape_manual(values = shape_set) +
  labs(
    y = "Fraction Edited",
    x = "Generations",
    color = "Replicate") +
  theme(
    axis.text.x = element_text(size = fig_font_size),
    axis.text.y = element_text(size = fig_font_size*.9),
    axis.title.y = element_text(size = fig_font_size*1.1),
    axis.title.x = element_text(size = fig_font_size*1.1),
    strip.background=element_blank(),
    panel.grid.minor=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = "none")

fig_2C
```
