---
title: "fig_2F.Rmd"
author: "Max Schubert"
date: "2/2/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(data.table)
require(scales)
library(ggpubr)
library(plotly)
#library(dplyr)

library(cowplot)

library(ggbeeswarm) #first install.packages("ggbeeswarm")

# mkdir fig_nu2E
parent_folder <- here::here('fig_2F')
```



```{r get_data}
data_name = "het_output_df.csv"
data_file = paste(parent_folder, data_name, sep = "/")
data_dt <- data.table(fread(data_file))
data_dt[is.na(A), A := 0]
data_dt[is.na(C), C := 0]
data_dt[is.na(G), G := 0]
data_dt[is.na(T), T := 0]
data_dt[is.na(D), D := 0]
```


```{r metadata}
#manifest, describing each sample sequenced
manifest_name = "k171819_liblist.csv"
manifest_file = paste(parent_folder, manifest_name, sep = "/")
manifest_dt <- data.table(fread(manifest_file))
manifest_dt[, c("i7", "i7seq", "i5", "i5seq"):=NULL] #rm extraneous columns

#tx list, describing each transformation performed
txlist_name = "tx_list.csv"
txlist_file = paste(parent_folder, txlist_name, sep = "/")
txlist_dt <- data.table(fread(txlist_file))

#describe ref and alt for all positions
ref_alt_name = "het_pos_ref_alt.csv"
ref_alt_file = paste(parent_folder, ref_alt_name, sep = "/")
ref_alt_dt <- data.table(fread(ref_alt_file))
#adapt_dt[, c("5prime_cutadapt", "3prime_cutadapt", "5prime_edit", "3prime_edit"):=NULL] #rm extraneous columns

##merge metadata
tx_annot <- txlist_dt[ref_alt_dt, on = "locus_allele", nomatch = 0, allow.cartesian=TRUE] #add "ref" and "alt" sequences expected, expanding for all "pos"
tx_annot[, c("strain", "plasmid", "MMR", "controltype"):=NULL]

metadata <- manifest_dt[tx_annot, on = "tx", nomatch = 0, allow.cartesian=TRUE]
metadata[, c("ID", "well", "expt"):=NULL]


#merge counts onto metadata
data_dt[,uniq := sample]
annotated_data_dt <- data_dt[metadata, on = c("uniq", "pos")]


```

```{r calc_editing}


#melt data, label
annot_melt_data = melt(annotated_data_dt, id.var=c("V1", "sample", "pos", "uniq", "timepoint", "plate",
                                 "amplicon", "tx", "desc", "locus_allele", "donor_len", "ref", "alt", "status"), value.name = 'count', variable.name = "base_obs")

annot_melt_data[, is_ref := (base_obs == ref)]
annot_melt_data[, is_alt := (base_obs == alt)]
#of sequences matching ref or alt, what fraction is edited
#PAY ATTENTION TO THE "BY" here!!!! it's critical for assigning values to the appropriate experiments
annotated_het_fedit <- annot_melt_data[ is_ref ==TRUE | is_alt == TRUE, fraction_edited := (count/sum(count)) , by=c('uniq', 'pos')][is_alt == TRUE]



#annotated_dt <- annotated_dt[, all_count := sum(Count), by = 'uniq']
#annotated_countrefalt <- annotated_dt[is_ref ==TRUE | is_alt == TRUE][, ref_alt_count := sum(Count), by = 'uniq']
#annotated_countrefalt[, pct_ref_alt := ref_alt_count/all_count]
```



```{r set_up_het_plot}
#constants
tick_font_size = 12
axis_font_size = 12

#filter plot to look at subset
current = annotated_het_fedit
#current = annotated_fedit[locus_allele %in% c("rpoB_wide", "gyrA_ultrawide", "rpoB_plus", "gyrA_plus")]
current = current[donor_len == 90]
current = current[status == "editing"] 
#current = current[controltype != "negative_control"]
current = current[timepoint == 1]

#label by oligo position
current[locus_allele == "rpoB_het_full", oligo_pos := pos + 38]
current[locus_allele == "gyrA_het_full", oligo_pos := pos + 36]



#calculate pct editing across all 
#current_het_subset <- current[]


```



```{r plot_het}


fig_by_pos <- ggplot(current, aes(x= oligo_pos, y=fraction_edited, color=locus_allele)) + 
  geom_jitter(size = 3, alpha = 0.7, stroke = 0, width = 0.15, height = 0.01) +
  #geom_quasirandom(method='pseudorandom', size = 3, alpha = 0.7, stroke = 0)+
  #geom_hline(yintercept=mean_locus_editing, linetype=2, size=0.5) +
  theme_linedraw() +
  #coord_cartesian(ylim=c(.5, .95)) +
  scale_y_continuous(breaks = c(.5, .6, .7, .8, .9),
                     labels = c("50%","60%", "70%", "80%", "90%"),
                     limits = c(.5, .8)) +
  scale_x_continuous(breaks = c(35, 45, 55),
                     labels = c('35', '45', '55'),
                     limits = c(35,55)) +
  labs(x = "Heterology Position\n(bases)", y = "Fraction Edited")  +
  #facet_grid(~donor_len, scales = 'free_x', space = 'free_x',
  #           switch = 'both')  #+ #scales='free_x'
  #scale_colour_manual(values = color_2d) +
  theme(
    axis.text.x = element_text(size = tick_font_size),
    axis.text.y = element_text(size = tick_font_size),
    axis.title = element_text(size = axis_font_size),
    #strip.background=element_blank(),
    panel.grid.minor=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = 'none')

fig_by_pos
```

```{r plot_full_editing}
het_full_retreive = readRDS(file = paste(parent_folder, "het_full_slice.rds", sep = "/"))
het_full_retreive$pos = "Fully edited"

color_2d <- c('gyrA_het_full' = '#F8766D', 'rpoB_het_full' = '#00BFC4')

fig_full <- ggplot(het_full_retreive, aes(x= pos, y=fraction_all_edited, color=locus_allele)) + 
  geom_jitter(size = 3, alpha = 0.7, stroke = 0, width = 0.15, height = 0.01) +
  #geom_quasirandom(method='pseudorandom', size = 3, alpha = 0.7, stroke = 0)+
  #geom_hline(yintercept=mean_locus_editing, linetype=2, size=0.5) +
  theme_linedraw() +
  #coord_cartesian(ylim=c(.5, .95)) +
  scale_y_continuous(breaks = c(.5, .6, .7, .8, .9),
                     labels = c("50%","60%", "70%", "80%", "90%"),
                     limits = c(.5, .8)) +
  labs( x= "Fully\nedited", color = "Locus")  +
  #facet_grid(~donor_len, scales = 'free_x', space = 'free_x',
  #           switch = 'both')  #+ #scales='free_x'
  scale_colour_manual(values = color_2d) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = element_blank(),
    axis.title.x = element_text(size = fig_font_size),
    axis.title.y = element_blank(),
    #strip.background=element_blank(),
    panel.grid.minor=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line(),
    legend.position = 'none')

fig_full
```


```{r line_up_plots}
fig_new_2F = plot_grid(fig_by_pos, fig_full, align = "h", rel_widths = c(1, .25))
fig_new_2F
```

```{r save_plots}
fig_width = 3
fig_height = 2.9 #

ggsave(here::here('fig_2F_out.pdf'), plot=fig_new_2F, width=fig_width, 
       height=fig_height, units='in', dpi=300, device = cairo_pdf)
```



