---
title: "fig1d"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(gridExtra)
library(here)
library(ggpubr)
library(here)

parent_folder <- here::here('fig_1d')
```


```{r get_data}
#this is the file with minimum counts 20
mergebinpath <- paste(parent_folder,"ev1_edit_merged_bins", sep = "/" )
merged_bins.dt <- data.table(fread(mergebinpath))
mergemelt.dt <- melt(merged_bins.dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')

mergemelt.dt[, sample_ID := str_replace_all(Sample, "_cutcount", "")]

#import library annotations, trim some extraneous columns, trim some extraneous rows
liblistpath <- paste(parent_folder,"lib_list.csv", sep = "/" )
liblistdt <- data.table(fread(liblistpath))

liblistdt[, c("id",
              "column",
              "row"):=NULL]

annotated_megatable <- liblistdt[mergemelt.dt, on = "sample_ID", nomatch = 0]


#read in edit seqs (ref, alt)
refaltpath <- paste(parent_folder,"adapters_map.csv", sep = "/" )
refalt_dt <- data.table(fread(refaltpath))

refalt_dt[, c("5prime_cutadapt",
              "3prime_cutadapt",
              "5prime_edit",
              "3prime_edit"):=NULL]
#merge ref and alt to table
#for now, using expt_set, though in the future something more complex should be used
seq_annotated_megatable <- annotated_megatable[refalt_dt, on = "expt_set", nomatch = 0]

```

```{r calc_editing}
#establishes control sample and normalizes to this, prints into "ratio", kill singletons
seq_annotated_megatable[, is_ref := (bc_read == ref)]
seq_annotated_megatable[, is_alt := (bc_read == alt)]

edited_frac <- seq_annotated_megatable[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := 1- (Count/sum(Count)) , by='Sample'][is_ref == TRUE]

```

```{r plot_with_hours}
######
currenttable = edited_frac[expt_set == "ev_gyr"] #set experiment to view

#load table of timepoint ~ hours, merge hours to current table
hours_path <- paste(parent_folder,"timepoint_hours.csv", sep = "/" )
hours.dt <- data.table(fread(hours_path))
current_table_hours <- currenttable[hours.dt, on = "timepoint", nomatch = 0]

#define means
summary <- current_table_hours[,
                        list(
                          Count = Count,
                          N= .N,
                          fraction_edited= mean(fraction_edited),
                          sd= sd(fraction_edited),
                          se= sd(fraction_edited) / sqrt(.N)),
                        by=c("timepoint", "hours")]


#plot, tall skinny version for figure 1
ggplot(current_table_hours, aes(x=hours, y=fraction_edited, color = "#F8766D")) + 
  #geom_errorbar(data = summary, aes(ymin=fraction_edited-se, ymax=fraction_edited+se, alpha = .3), width=.1) +
  geom_line(data = summary, aes(x = hours, y= fraction_edited, alpha = .3)) +
  geom_jitter(width = 0.5,  size = 3) +
  scale_y_continuous(breaks = c(.00, .1, .25, .5, .75, .9, 1)) +
  theme_bw() +
  theme(text = element_text(size=18)) +
  labs(
    x = "Time (Hours)",
    y = "Fraction Edited") +
  theme(legend.position = "none") +
  coord_fixed(ratio = 80)

```
