---
title: "Figures"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)
library(gridExtra)
library(here)
library(ggpubr)

parent_folder <- "/Users/Max_Schubert/Dropbox/RLR_e.coli_dropbox/rlr_git"
```


```{r fig1_load_data_and_metadata}
#from b22 analysis
fig1c_dir = "fig_1c"
current_folder <- paste(parent_folder, fig1c_dir, sep = '/')

#read in data
edit_data_file = paste(current_folder,"b18b19b23_edit_mergedbins", sep = "/")
edit_data_dt <- data.table(fread(edit_data_file))
edit_data_melt <- melt(edit_data_dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
#make new col Sample_num for merging to manifest
edit_data_melt[, Sample_num := as.numeric(str_replace_all(Sample, "_cutcount", ""))]

#import manifest
#this contains the data "expt_set" and "tx" for annotating metadata!
manifest_file = paste(current_folder, "FC_04592_1234_PF_mm1_mschubert_manifest_edited.csv", sep = "/")
manifest_dt <- data.table(fread(manifest_file)) 
#kill a ton of these columns
manifest_dt = Filter(function(x)!all(is.na(x)), manifest_dt) #kills columns with all NA
manifest_dt = manifest_dt[,c('Sample_num','expt_set','well_indexed','tx','editing_timepoint', 'control_status')] #keeps only specified columns

#merge manifest to edit_data
melt_with_annot <- edit_data_melt[manifest_dt, on = "Sample_num", nomatch = 0]

#import metadata, merge 
tx_deets_file = paste(current_folder, 'edit_tx_map.csv', sep = "/")
tx_deets = data.table(fread(tx_deets_file)) 
melt_with_metadata <- melt_with_annot[tx_deets, on = c("expt_set","tx"), nomatch = 0]

#import ref_alt, merge
ref_alt_file = paste(current_folder, 'ref_alt_map.csv', sep = "/")
ref_alt = data.table(fread(ref_alt_file)) 
melt_with_metadata2 <- melt_with_metadata[ref_alt, on = "adapters", nomatch = 0]

```

```{r fig1c_ref_alt}
#establishes control sample and normalizes to this, prints into "ratio", kill singletons
melt_with_metadata2[, is_ref := (bc_read == ref)]
melt_with_metadata2[, is_alt := (bc_read == alt)]

melt_with_fedit <- melt_with_metadata2[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := 1- (Count/sum(Count)) , by='Sample_num'][is_ref == TRUE]

```


```{r fig1c_plot}
#to make Xlabels have multiple lines, instead of comma and space:
addline_format <- function(x,...){
  gsub(', ','\n',x)
}

#looking first at b22 samples
#optional filters
b22 <- melt_with_fedit[expt_set == 'b22']
b22 <- b22[control_status != 'background']

#look only at controls
b22controls <- melt_with_fedit[expt_set == 'b22' & control_status == 'background']
#basically, no edited sequence was ever detected for controls


#change plot order of genotypes, specify statistical comparisons
b22$strain_genotype <- factor(b22$strain_genotype, levels = c("WT","∆mutS",
                                                              "∆mutS, ∆sbcB",
                                                              "∆mutS, ∆recJ",
                                                              "∆mutS, ∆recJ, ∆sbcB"))
my_comparisons <- list( c("WT", "∆mutS"), c("∆mutS", "∆mutS, ∆sbcB"),
                        c("∆mutS, ∆sbcB","∆mutS, ∆recJ"), c("∆mutS, ∆recJ", "∆mutS, ∆recJ, ∆sbcB") )
x_labels <- addline_format(c("WT", "∆mutS", "∆mutS, ∆sbcB", "∆mutS, ∆recJ", "∆mutS, ∆recJ, ∆sbcB"))


ggplot(b22, aes(x=strain_genotype, y=fraction_edited, color=adapters)) + 
  geom_jitter(width = 0.1, height = 0.1, size = 3) +
  theme_bw() +
  #scale_x_discrete(labels = addline_format(c("Background, control", "WT", "∆mutS", "∆mutS, ∆sbcB", "∆mutS, ∆recJ", "∆mutS, ∆recJ, ∆sbcB"))) +#limit=c(0.0005, 8),) +
  scale_y_continuous(breaks = c(.00001, .0001, .001, .01, .1, .25), 
                     trans = log10_trans()) +
  theme(text = element_text(size=18)) +
  labs(
    x = "Genotype",
    y = "Fraction Edited",
    title = "Effect of genotype on editing efficiency, sequencing results",
    color = "Locus") + # Add pairwise comparisons p-value
  stat_compare_means(comparisons = my_comparisons, method = "t.test", label = "p.signif") +
  scale_x_discrete(labels = x_labels)

```


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
