---
title: "simple read_allocation model"
output: html_document
---

## Setting variables

```{r}

library(data.table)
library(stringr)
library(plyr)
require(ggplot2)
require(data.table)
require(scales)

rate_a = 2
rate_b = 6
rate_c = 3
rate_d = 4
timepoints= 5
wt = 'c'

strain_a <- rate_a^(0:timepoints)
strain_b <- rate_b^(0:timepoints)
strain_c <- rate_c^(0:timepoints)
strain_d <- rate_d^(0:timepoints)

reads <- data.table(t=0:timepoints, a=strain_a, b=strain_b, c=strain_c, d=strain_d)
reads <- melt(reads, id.vars='t', variable.name='strain', value.name='cells')

reads[, pct := cells/sum(cells), by=t]
```

```{r}
ggplot(reads, aes(x=t, y=pct, color=strain)) + geom_line() + geom_point() +
  labs(title='percentage of reads per strain over time')

ggplot(reads, aes(x=t, y=log2(pct), color=strain)) + geom_line() + geom_point() +
  labs(title='log percentage of reads per strain over time')

reads[, rel_wt := pct/pct[strain==wt], by='t'] 

ggplot(reads, aes(x=t, y=rel_wt, color=strain)) + geom_line() + geom_point() +
  labs(title='strain growth relative to wildtype')

ggplot(reads, aes(x=t, y=log2(rel_wt), color=strain)) + geom_line() + geom_point() +
  labs(title='log strain growth relative to wildtype')
```

```{r}
lm_group <- function(dt_subset) {
  lmod <- lm(log2(rel_wt) ~ t, data= dt_subset)
  return(list(intercept= lmod$coefficients[1], slope= lmod$coefficients[2]))
}

read_slopes <- reads[, lm_group(.SD), by='strain']
read_slopes

```
