---
title: "fig_s3"
author: "Max Schubert"
date: "2/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(data.table)
require(scales)
library(ggpubr)
library(plotly)
#library(dplyr)

library(ggbeeswarm) #first install.packages("ggbeeswarm")

parent_folder <- here::here('supplemental_figures/fig_s3')
```


##additional plotting: TAA/TAG mismatch efficiency
```{r fetch hda and coaD 1bp data}
h10_name = 'h10fraction_edited.rds'
h10dir = paste(here::here('fig_2D'),h10_name,sep = "/")
h10_dt = readRDS(h10dir)

h10_dt = h10_dt[locus %in% c("hda", "coaD")]

h10_dt[,allele := tstrsplit(more_desc, "_", fixed=TRUE)[3]]

h10_dt[,c("read_id", "total_count", "bc_read", "col",
          "plas","ref", "alt", "parent", "Sample", "more_desc") := NULL]
```



```{r set up tags plot}
annotated_fedit = readRDS(file = paste(parent_folder, "fraction_edited_fig2e_plus.rds", sep = "/")) ####

#temp, filter plot to look at subsets
tagsdt = annotated_fedit[amplicon %in% c("hda", "coaD")] 
tagsdt = tagsdt[timepoint == 1]
tagsdt[, c("total_count", "bc_read", "uniq", "timepoint", "plate", "ID",
           "amplicon", "controltype", "tx", "plasmid",
           "ref", "alt", "is_ref","is_alt", "MMR", "strain") := NULL]

tagsdt[,c("locus", "allele") := tstrsplit(locus_allele, "_", fixed=TRUE)]


current = rbind(tagsdt, h10_dt, fill = TRUE)

#constants
tick_font_size = 10
axis_font_size = 10

#change plotting order
current$allele <- factor(current$allele ,levels = c("TAA","his","strep" ))


colors2 <- c('coaD' = '#F564E3','hda' = '#00B4F0')

```
## 
```{r tags}

tags <- ggplot(current, aes(x= allele, y=fraction_edited, color=locus)) + 
  geom_jitter(size = 3, alpha = 0.7,
              stroke = 0, width = 0.2) +
  #geom_quasirandom(method='pseudorandom', size = 3, alpha = 0.7, stroke = 0)+
  #geom_hline(yintercept=mean_locus_editing, linetype=2, size=0.5) +
  theme_linedraw() +
  #coord_cartesian(ylim=c(.5, .95)) +
  scale_y_continuous(breaks = c(.01, .05, .1, .25, .5, 1),
                     labels = c("1%","5%", "10%", "25%", "50%", "100%"),
                     limits = c(.01, 1),
                     trans = log10_trans()) +
  scale_x_discrete(labels = c("TAG > TAA\n1bp\nmismatch", "6xHis Tag\n18bp\ninsertion", "Strep Tag\n24bp\ninsertion")) +
  scale_colour_manual(values = colors2) +
  labs(x= "",
       y = "Fraction Edited",
       color = "Locus")  +
  annotation_logticks(sides = "l") +
  #scale_color_discrete(name = "Edit Type", labels = c("6xHis Tag (18bp)", "Strep Tag (24bp)", "TAG>TAA (1bp mismatch)")) +
  #facet_grid(~as, scales = 'free_x', space = 'free_x',
  #           switch = 'both')  + #scales='free_x'
  #scale_colour_manual(values = color_2d) +
  theme(
    axis.text.x = element_text(size = tick_font_size),
    axis.text.y = element_text(size = tick_font_size),
    axis.title.y = element_text(size = axis_font_size),
    axis.title.x = element_blank(),
    #strip.background=element_blank(),
   # panel.grid.minor=element_blank(),
    #panel.grid.major.x=element_blank(),
    panel.border=element_blank(),
    axis.line=element_line())

tags
```

```{r get_is5_data}
is5parent_folder <- parent_folder
#perform same functions for is5 experiment isolates
is5_data_name = "zz3_is5_variants.csv"
is5_data_file = paste(is5parent_folder, is5_data_name, sep = "/")
is5_data_dt <- data.table(fread(is5_data_file))

#trim extraneous columns
is5_data_dt[, c("VARIANT_SET_LABEL", "INFO_PQR", "INFO_QR", "INFO_NS", "INFO_ODDS",  "UID", "INFO_EPPR", "INFO_LOF", "INFO_DPB", "INFO_GTI", "IS_SV",
                   "INFO_MQMR", "INFO_RPPR", "INFO_NMD","INFO_PRO", "INFO_RO", "INFO_SRF",
                   "INFO_SRP", "INFO_SRR", "RO", "GT", "GQ",  "AO", "QA",  "QR", "INFO_MQM",
                   "INFO_ABP", "INFO_TECHNOLOGY.ILLUMINA", "INFO_EPP", "INFO_PQA", "INFO_RUN",
                   "INFO_DPRA", "INFO_QA", "INFO_EFF_EFFECT", "INFO_TYPE", "INFO_PAO", "INFO_CIGAR",
                   "INFO_PAIRED", "INFO_AO", "INFO_SAP", "INFO_RPR", "INFO_RPP", "INFO_AC",
                   "INFO_AB",  "INFO_EFF_TRLEN",  "INFO_EFF_AA", "INFO_RPL",  "INFO_EFF_WARN",
                   "INFO_EFF_ERR", "INFO_EFF_GT", "INFO_EFF_CLASS", "INFO_MEANALT", "INFO_EFF_RANK",
                   "INFO_EFF_CODING", "INFO_EFF_TR", "PHRED_ENCODING", "CHROMOSOME", "INFO_DP",
                   "INFO_NUMALT", "INFO_AN", "INFO_LEN", "IS_HET", "INFO_EFF_BIOTYPE",
                "INFO_SAR","INFO_SAF","INFO_AF","GL","INFO_EFF_CONTEXT", "INFO_EFF_IMPACT","INFO_EFF_GENE", "REF", "ALT") := NULL]
```

#s3b
```{r plot_is5}

#estimate number of edited sites
is5_data_dt[,approx_is5_edits := round(AF*12)]


is5_fig <- ggplot(is5_data_dt, aes(approx_is5_edits)) + #x=as.factor(POSITION), aes( y=approx_is5_edits)
  geom_histogram(size = 3, alpha = 0.7, stat = "count") + #height = 0.05,stroke = 0
  scale_x_discrete(labels = c("Retron targeting IS5\n(12 copies)\n6bp insertion")) +
  labs(
    x = "IS elements inactivated\n(Estimate per 12 copies), per isolate",
    y = "Number of isolates, of 12") +
  scale_y_continuous(breaks = c(0,1,2,3,4,5), limits= c(0,5)) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7), limits = c(0,7), labels = c("0", "1", "2", "3", "4", "5", "6", "7"))+
  theme_linedraw() +
  theme(
    text = element_text(size=tick_font_size),
    axis.text = element_text(size = tick_font_size),
    axis.title = element_text(size = tick_font_size),
    panel.border=element_blank(),
    axis.line=element_line(),
    panel.grid.major.x=element_blank(),
    panel.grid.minor.x=element_blank(),
    panel.grid.minor.y=element_blank(),
)

is5_fig

```

```{r combine_figures}

combined = plot_grid(tags, is5_fig, align = "h", rel_widths = c(1.5, 1))
combined
```




```{r save_figure}
fig_width = 6
fig_height = 3 #edit of X,y axis makes it shorter

ggsave(here::here('/supplemental_figures/fig_s3_out.pdf'), plot=combined,
       width=fig_width, height=fig_height,
       units='in', dpi=300, device = cairo_pdf)
#ggplotly()
```
