---
title: "fig_s4A"
author: "Max Schubert"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#load libraries
library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(data.table)
require(scales)
library(ggpubr)
library(RColorBrewer)

library(here)

parent_folder <- here::here('supplemental_figures/fig_s4A')
source(here::here('constants.R'))
```
```{r get_data}

#paths to data tables, output by matlab
base_path = parent_folder
more_path = parent_folder

gp1a = paste(base_path,"GP1_A.csv", sep = "/" )
gp2a = paste(base_path,"GP2_A.csv", sep = "/" )
gp2b = paste(base_path,"GP2_B.csv", sep = "/" )
#plate 3
gp3a_more = paste(more_path,"GP3_A.csv", sep = "/" )
gp3b_more = paste(more_path,"GP3_B_2.csv", sep = "/" )

platemap = paste(base_path, "plate_map.csv", sep = "/")
txs = paste(base_path, "tx_map.csv", sep = "/")


#make into datatables
gp1a.dt = data.table(fread(gp1a))
gp2a.dt = data.table(fread(gp2a))
gp2b.dt = data.table(fread(gp2b))
#gp3a.dt = data.table(fread(gp3a))
#gp3b.dt = data.table(fread(gp3b))
gp3a_more.dt = data.table(fread(gp3a_more))
gp3b_more.dt = data.table(fread(gp3b_more))

platemap.dt = data.table(fread(platemap))
txmap.dt = data.table(fread(txs))

```

```{r label, normalize}
#label all the plates, including replicates, rbind all data together

gp1a.dt$plate = 1
gp2a.dt$plate = 2
gp2b.dt$plate = 2
#gp3a.dt$plate = 3
#gp3b.dt$plate = 3
gp1a.dt$rep = "a"
gp2a.dt$rep = "a"
gp2b.dt$rep = "b"
#gp3a.dt$rep = "a"
#gp3b.dt$rep = "b"
gp3a_more.dt$plate = 3
gp3b_more.dt$plate = 3
gp3a_more.dt$rep = "a"
gp3b_more.dt$rep = "b"
combined = rbind(gp1a.dt, gp2a.dt, gp2b.dt, gp3a_more.dt, gp3b_more.dt)

#merge tx desc onto platemaps, producing metadata, ditch some columns
metadata <- platemap.dt[txmap.dt, on = "tx", nomatch = 0]
metadata[,c( "oligo","seq","soft_desc","recov") :=NULL]

#merge metadata onto data on tx on plate, well
total_merged <- combined[metadata, on = c("plate", "well"), nomatch = 0]

### normalize
total_merged[, mean_WT := mean(mu_hourly[hard_desc == "WT"]), by=c('plate', 'rep')]

#total_merged[, mu_normal := mu_hourly/mean_WT, by=c('plate', 'well')]

# subtract WT rate instead of adding
total_merged[, mu_normal := mu_hourly/mean_WT, by=c('plate', 'well')]

```
```{r plot}
into_plot <- total_merged[total_merged$comments != 'very late growth?', ]
into_plot[, mu_allele := median(mu_normal), by=c('hard_desc')] #mean of mu

#abbreviate name for 1594 deletion
into_plot[hard_desc == "rpoB_CACTCGGCCCAG_1594_nan",
          hard_desc := "rpoB_1594∆12bp"]

#new version
fig_s4A <- ggplot(into_plot,
                  aes(x=reorder(hard_desc,mu_normal),y=mu_normal)) +
  #geom_jitter(height = 0.0, width = 0.2,
  #            size = 2, alpha = 0.5, stroke = 0) + 
  geom_boxplot( alpha = 0.7, outlier.shape = NA) +
  theme_linedraw() +
  scale_y_continuous(breaks = c(.5,.75,1,1.25, 1.5,1.75,2),
                     trans = log10_trans()) +
  labs( y = "Clonal Growth Rate\n5ug/mL Rif (normalized)") +
  theme(axis.text.x = element_text(angle =60, vjust = 1, hjust=1,
                                   size = fig_font_size),
        axis.text.y = element_text(size = fig_font_size),
        panel.grid.minor.x=element_blank(),
        axis.title.y = element_text(size = fig_title_font_size),
        axis.title.x = element_blank())

fig_s4A

```
```{r save_figure}
ggsave(here::here('supplemental_figures/fig_S4A.pdf'), plot=fig_s4A, width=4, 
       height=3, units='in', dpi=300, device = cairo_pdf)
```





##optional: export this data for analysis in figure 4C
```{r export_for_4C}
summary3C <- ddply(into_plot, "hard_desc", summarise,
                           N    = sum(!is.na(mu_normal)),
                           median = median(mu_normal, na.rm=TRUE),
                           mean = mean(mu_normal, na.rm=TRUE),
                           sd   = sd(mu_normal, na.rm=TRUE),
                           se   = sd / sqrt(N)
)

write_path = here::here('fig_4C_linmod')
write.csv(summary3C,paste(write_path, 'summary_growth_out.csv', sep = "/"))

```


