---
title: "fig_s2b"
author: "Max Schubert"
date: "8/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup}
library(data.table)
library(stringr)
require(ggplot2)
require(data.table)
require(scales)
library(here)

parent_folder <- here::here()

source(here::here('constants.R'))
```

#load and process data. These steps identical to fig2B analysis

```{r load_data_and_metadata}
fig2f_dir = "fig_2B"
current_folder <- paste(parent_folder, fig2f_dir, sep = '/')

#read in data
edit_data_file = paste(current_folder,"b18b19b23_edit_mergedbins", sep = "/")
edit_data_dt <- data.table(fread(edit_data_file))
edit_data_melt <- melt(edit_data_dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
#make new col Sample_num for merging to manifest
edit_data_melt[, Sample_num := as.numeric(str_replace_all(Sample, "_cutcount", ""))]

#import manifest
#this contains the data "expt_set" and "tx" for annotating metadata!
manifest_file = paste(current_folder, "FC_04592_1234_PF_mm1_mschubert_manifest_edited.csv", sep = "/")
manifest_dt <- data.table(fread(manifest_file)) 
#kill a ton of these columns
manifest_dt = Filter(function(x)!all(is.na(x)), manifest_dt) #kills columns with all NA
manifest_dt = manifest_dt[,c('Sample_num','expt_set','well_indexed','tx','editing_timepoint', 'control_status')] #keeps only specified columns

#merge manifest to edit_data
melt_with_annot <- edit_data_melt[manifest_dt, on = "Sample_num", nomatch = 0]

#import metadata, merge 
tx_deets_file = paste(current_folder, 'edit_tx_map.csv', sep = "/")
tx_deets = data.table(fread(tx_deets_file)) 
melt_with_metadata <- melt_with_annot[tx_deets, on = c("expt_set","tx"), nomatch = 0]

#import ref_alt, merge
ref_alt_file = paste(current_folder, 'ref_alt_map.csv', sep = "/")
ref_alt = data.table(fread(ref_alt_file)) 
melt_with_metadata2 <- melt_with_metadata[ref_alt, on = "adapters", nomatch = 0]

```

```{r ref_alt}
#establishes control sample and normalizes to this, prints into "ratio", kill singletons
melt_with_metadata2[, is_ref := (bc_read == ref)]
melt_with_metadata2[, is_alt := (bc_read == alt)]

melt_with_fedit <- melt_with_metadata2[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := (Count/sum(Count)) , by='Sample_num'][is_alt == TRUE]

```


### set up figure
```{r setup_fig_s2b}
#to make Xlabels have multiple lines, instead of comma and space:
addline_format <- function(x,...){
  gsub(', ','\n',x)
}

x_labels <- addline_format(c("∆recJ, ∆sbcB","∆recJ, ∆sbcB, +mutL*","∆mutS, ∆recJ, ∆sbcB","∆mutS, ∆recJ, ∆sbcB, +mutL*"))

#filter for fig1E data
b19 <- melt_with_fedit[expt_set == 'b19']
#show second timepoint
b19 <- b19[editing_timepoint == 2]
```


```{r plot_fig_s2b}
fig_s2b <- ggplot(b19, aes(x=interaction(plas_desc, strain_genotype), y=fraction_edited,  color = adapters)) + 
  geom_jitter(width = 0.25, height = 0.1, size = 3,
              alpha = 0.7, stroke = 0) +
  theme_linedraw() +
  scale_y_continuous(breaks = c(seq.int(.01, .09, .01), seq.int(.1, 1, .1)),
                     limits = c(0.01,1),
                     labels = c('1%',rep("",8), '10%', rep("",3), '50%', rep("",4), '100%'),
                     trans = log10_trans()) +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_line(size =  1),
        axis.title.y = element_text(size = fig_title_font_size),
        axis.text.y = element_text(size = fig_title_font_size),
        panel.border=element_blank(),
        axis.line=element_line(),
        panel.grid.minor.y=element_blank(),
        panel.grid.major.y=element_blank(),
        legend.position = c(0.75, 0.2),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.direction = "vertical") +
  #rotate_x_text(angle = 45) + 
  labs(
    x = "",
    y = "Fraction Edited",
    color = "Locus") +
  scale_x_discrete(labels = x_labels)

fig_s2b
```

```{r save_plot}
ggsave(here::here('supplemental_figures/fig_s2b_out.pdf'), plot=fig_s2b,
       width=3, height=3,
       units='in', dpi=300, device = cairo_pdf)
```


