---
title: "FigureS1b_s6a"
author: "Max Schubert"
date: "8/2/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(stringr)
library(plyr)
library(gridExtra)
require(ggplot2)
require(scales)
library(ggpubr)
library(plotly)
library(here)


parent_folder = here::here('supplemental_figures/fig_s1b_s6a')

```

```{r read_in_data}
#data
edit_data_name = "h3_merge_bins_out_redo"
edit_data_file = paste(parent_folder, edit_data_name, sep = "/")
edit_data_dt <- data.table(fread(edit_data_file))
edit_data_melt <- melt(edit_data_dt, id.var=c('read_id', 'total_count', 'bc_read'), value.name='Count', variable.name='Sample')
#use Sample_ID to merge to metadata
edit_data_melt[, Sample_ID := as.numeric(str_replace_all(Sample, "_cutcount", ""))]

```

```{r read_in_metadata}
#manifest, describing the sample sequenced
manifest_name = "edit_info.csv"
manifest_file = paste(parent_folder, manifest_name, sep = "/")
manifest_dt <- data.table(fread(manifest_file))
#make smaller version to use as metadata
metadata = manifest_dt[, c("V1", "Sample_Plate", "adaptrset",
                "cutadapt_edit_5prime", "cutadapt_edit_3prime",
                "cutadapt_5prime", "cutadapt_3prime", "filename", "reads"):=NULL]

#merge manifest to edit_data
melt_with_annot <- edit_data_melt[metadata, on = "Sample_ID", nomatch = 0]
melt_with_annot_nozero = melt_with_annot[Count > 0] #kill zero values to make table smaller
```

# measure fraction edited
```{r fraction_edited}
melt_with_annot_nozero[, is_ref := (bc_read == ref)]
melt_with_annot_nozero[, is_alt := (bc_read == alt)]

#of sequences matching ref or alt, what fraction is edited
melt_with_fedit <- melt_with_annot_nozero[ is_ref ==TRUE | is_alt == TRUE , fraction_edited := (Count/sum(Count)) , by='Sample_ID'][is_alt == TRUE]
melt_with_fedit[, c("is_ref", "is_alt"):=NULL] #ditch these columns now
```

```{r keep track of reads}
total_counts_merged = sum(melt_with_annot_nozero$Count)
total_counts_ref_or_alt = sum(melt_with_annot_nozero[is_ref == TRUE | is_alt == TRUE]$Count)

#compare ref_alt read num to total merged
print(paste(as.character(total_counts_ref_or_alt/total_counts_merged*100), "% of reads merged are ref or alt seqs", sep = " "))

#hmmmm read in cutcount_reads_report
cutcount_name = "cutcount_reads_report.csv"
cutcount_file = paste(parent_folder, cutcount_name, sep = "/")
cutcount_dt <- data.table(fread(cutcount_file))

#num_reads_cutcounted = sum(cutcount_dt$tot_counts_cutcounted)
#OK.... i somehow cutcount-ed 21.8M reads...
```

##visualize the controls
# this is s1b, editing controls
```{r plot h1}
h1 <- melt_with_fedit[expt == 'H1']


#to make Xlabels have multiple lines, instead of comma and space:
addline_format <- function(x,...){
  gsub(', ','\n',x)
}

#change plot order of genotypes
h1$more_desc <- factor(h1$more_desc, levels = c("normal","gfp neg control",
                                                              "dRT",
                                                              "no beta",
                                                              "rc",
                                                              "rc, drt"))
#change legend order of plasmids
h1$desc <- factor(h1$desc, levels = c())
my_comparisons <- list( c("WT", "∆mutS"), c("∆mutS", "∆mutS, ∆sbcB"),
                        c("∆mutS, ∆sbcB","∆mutS, ∆recJ"), c("∆mutS, ∆recJ", "∆mutS, ∆recJ, ∆sbcB") )
x_labels <- addline_format(c("Full, Construct",
                             "GFP, negative, control",
                             "dRT, control",
                             "no SSAP, control",
                             "reverse-, complement, control",
                             "reverse-, complement, and dRT, control"))



fig_s1b = ggplot(h1, aes(x=more_desc, y=fraction_edited, color=more_desc)) + 
  geom_jitter(width = 0.1, height = 0.1, size = 3) +
  theme_bw() +
  geom_boxplot(outlier.shape = NA, alpha = 0.5) +
  theme(legend.position = "none") +
  scale_y_continuous(breaks = c(.0001, .001, .01, .1, .25, .5), 
                     trans = log10_trans(),
                     labels = c('.01%', '0.1%', '1%', '10%', '25%', '50%')) +
  theme(text = element_text(size=14)) +
  labs(
    x = "Condition",
    y = "Fraction Edited") +
  scale_x_discrete(labels = x_labels)

fig_s1b
#ggplotly()

ggsave(here::here('supplemental_figures/fig_s1b.pdf'),
       plot=fig_s2, width=7, height=5, units='in', dpi=300,
       useDingbats=FALSE) #this is so illustrator can interpret symbols
```

#h7
#s6a, CspRecT efficiency across genotypes
```{r}

h7 <- melt_with_fedit[expt == 'H7']

#manual fix for bMS_446, 453 genotypes
h7[parent == "bMS_446", genotype := "sbcB-, recJ-"]
h7[parent == "bMS_453", genotype := "sbcB-, recJ-, mutS-"] 


#save H7 for inclusion in figure 1B appended section
h7_scrubbed = copy(h7)
h7_scrubbed[, ssap := more_desc]
h7_scrubbed[, well := Sample_Well]
h7_scrubbed[, c("read_id", "total_count", "bc_read", "Sample", "Count",
       "Sample_ID", "expt", "time_point", "tx", "Sample_Well",
       "parent", "plas", "desc" , "notebook", "ref", "alt", "more_desc"):=NULL]

save_as = paste(parent_folder, "h7data", sep = "/")
saveRDS(h7_scrubbed, file = save_as)


#change plot order of genotypes, specify statistical comparisons
h7$genotype <- factor(h7$genotype, levels = c("WT",
                                              "sbcB-",
                                              "recJ-",
                                              "sbcB-, recJ-",
                                              "sbcB-, recJ-, mutS-"))
my_comparisons <- list( c("WT", "sbcB-"), c("sbcB-", "recJ-"),
                        c("recJ-","sbcB-, recJ-"), c("sbcB-, recJ-", "sbcB-, recJ-, mutS-") )

#x labels, greek characters as unicode
x_labels <- addline_format(c("WT","\u0394sbcB",
                             "\u0394recJ",
                             "\u0394sbcB, \u0394recJ",
                             "\u0394sbcB, \u0394recJ, \u0394mutS"))


make_percent <- function(x){
  paste(100*x, "%", sep="")
}

y_breaks = c(.001, .01, .1, .25, .5, 1)

fig_supp3 <- ggplot(h7, aes(x=genotype, y=fraction_edited, color=desc)) + 
  geom_jitter(width = 0.2, height = 0.05, size = 3) +
  theme_bw() +
  scale_y_continuous(breaks = y_breaks,
                     labels = make_percent(y_breaks),
                     trans = log10_trans()) +
  theme(text = element_text(size=18)) +
  labs(
    x = "Genotype",
    y = "Fraction Edited",
    title = "Effect of genotype on editing efficiency, using CspRecT SSAP",
    color = "Locus") + # Add pairwise comparisons p-value
  stat_compare_means(comparisons = my_comparisons,
                     method = "t.test",
                     label = "p.signif",
                     label.y = c(-1.4, -.9 , -.4, .1),
                     tip.length = 0.02 ) +
  scale_x_discrete(labels = x_labels)

ggsave(here::here('supplemental_figures/fig_s3A.pdf'), plot=fig_supp3,
       width=7, height=6, units='in', dpi=300,
       device = cairo_pdf)

fig_supp3
```

#figure S6C
```{r h4_slide}
h4 <- melt_with_fedit[expt == 'H4']

#manual fix for position column
ditch_pre <- function(x,...){
  gsub('gyrA_pos_','',x)
}
ditch_post <- function(x,...){
  gsub('_MAGEoligo','',x)
}

h4[,position := as.integer(ditch_post(ditch_pre(more_desc)))]
h4_no_negative = h4[desc != "is5"]

y_breaks = c(.1, .25, .5, .9, 1)
x_breaks = c(10, 20, 30, 40, 50 , 60 , 70 , 80 , 90)

fig_s6c <- ggplot(h4_no_negative, aes(x=position, y=fraction_edited, color=as.factor(position))) + 
  geom_jitter(width = 0.3, size = 2, alpha = 0.7) +
  geom_boxplot(outlier.shape = NA, alpha = 0.5) +
  theme_linedraw() +
  scale_y_continuous(breaks = y_breaks,
                     labels = make_percent(y_breaks), trans = log10_trans()) +
  scale_x_continuous(breaks = x_breaks) +
  theme(text = element_text(size=18),
        legend.position = "none") +
  labs(
    x = "Heterology position (90-mer donor)",
    y = "Fraction Edited") 

fig_s6c

ggsave(here::here('supplemental_figures/fig_s6c.pdf'), plot=fig_supp3B,
       width=5, height=3, units='in', dpi=300,
       useDingbats = FALSE)
#ggplotly()
```
